/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PckInterfaces;

import PckConexion.ClsConexion;
import PckEntidad.ClsEntidadNivel;
import PckEntidad.ClsEntidadPeriodo;
import PckNegocio.ClsMatricula;
import PckNegocio.ClsNivel;
import PckNegocio.ClsPeriodo;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import mpsDAL.MatriculaDAL;
import mpsEntity.MatriculaEntity;

/**
 *
 * @author Kevin
 */
public class AjusteVencimientoMes extends javax.swing.JPanel {

    private static final String LOGOTIPO = System.getProperty("user.dir")+"/Img/solr.jpg";
    
    SimpleDateFormat formatoOriginal = new SimpleDateFormat("yyyy-MM-dd");
    
    List<String> listIdNivel = new ArrayList();
    List<String> listIdPeriodo = new ArrayList();
    
    MatriculaDAL matriculaDAL = new MatriculaDAL();
    
    Date date = new Date();
    
    /**
     * Creates new form ReporteDeudaMonto
     */
    public AjusteVencimientoMes() {
        initComponents();
        
        jdcVencimiento.setDate(date);
        
        rbnGrupo.add(rbnLonchera);
        rbnGrupo.add(rbnMensualidad);
        
         CargarComboNivel(); 
        if(cmbNivel.getSelectedIndex() != -1) {
            CargarComboPeriodo();
        }    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        rbnGrupo = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        pnlDerecha = new javax.swing.JPanel();
        pnlBot = new javax.swing.JPanel();
        btnEditarFecha = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cmbNivel = new javax.swing.JComboBox<>();
        cmbPeriodo = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        rbnLonchera = new javax.swing.JRadioButton();
        rbnMensualidad = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jdcVencimiento = new com.toedter.calendar.JDateChooser();
        jLabel17 = new javax.swing.JLabel();
        cmbMes = new javax.swing.JComboBox<>();

        setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(237, 240, 242));
        jPanel4.setPreferredSize(new java.awt.Dimension(911, 50));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jPanel5.setBackground(new java.awt.Color(237, 240, 242));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Droid Sans", 1, 12)); // NOI18N
        jLabel1.setText("AJUSTE DE VENCIMIENTO POR MES");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        jPanel5.add(jLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        jPanel4.add(jPanel5, gridBagConstraints);

        add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(237, 240, 242));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        pnlDerecha.setBackground(new java.awt.Color(255, 255, 255));
        pnlDerecha.setPreferredSize(new java.awt.Dimension(300, 400));
        pnlDerecha.setLayout(new java.awt.BorderLayout());

        pnlBot.setBackground(new java.awt.Color(255, 255, 255));
        pnlBot.setLayout(new java.awt.GridBagLayout());

        btnEditarFecha.setFont(new java.awt.Font("Droid Sans", 1, 12)); // NOI18N
        btnEditarFecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PckIconos/ic_mode_edit_black_24dp.png"))); // NOI18N
        btnEditarFecha.setText("EDITAR FECHA VENCIMIENTO");
        btnEditarFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarFechaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        pnlBot.add(btnEditarFecha, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jLabel5.setText("Nivel.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 0);
        pnlBot.add(jLabel5, gridBagConstraints);

        cmbNivel.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        cmbNivel.setMinimumSize(new java.awt.Dimension(300, 20));
        cmbNivel.setPreferredSize(new java.awt.Dimension(500, 20));
        cmbNivel.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbNivelItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        pnlBot.add(cmbNivel, gridBagConstraints);

        cmbPeriodo.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        cmbPeriodo.setMinimumSize(new java.awt.Dimension(300, 20));
        cmbPeriodo.setPreferredSize(new java.awt.Dimension(500, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 20);
        pnlBot.add(cmbPeriodo, gridBagConstraints);

        jLabel13.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jLabel13.setText("Servicio.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        pnlBot.add(jLabel13, gridBagConstraints);

        jLabel14.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jLabel14.setText("Periodo.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        pnlBot.add(jLabel14, gridBagConstraints);

        rbnLonchera.setBackground(new java.awt.Color(255, 255, 255));
        rbnLonchera.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        rbnLonchera.setSelected(true);
        rbnLonchera.setText("Servicio lonchera");
        rbnLonchera.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbnLoncheraItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 20);
        pnlBot.add(rbnLonchera, gridBagConstraints);

        rbnMensualidad.setBackground(new java.awt.Color(255, 255, 255));
        rbnMensualidad.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        rbnMensualidad.setText("Mensualidades");
        rbnMensualidad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbnMensualidadItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 20);
        pnlBot.add(rbnMensualidad, gridBagConstraints);

        jSeparator1.setForeground(new java.awt.Color(237, 240, 242));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(30, 10, 0, 10);
        pnlBot.add(jSeparator1, gridBagConstraints);

        jLabel16.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jLabel16.setText("Mes.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        pnlBot.add(jLabel16, gridBagConstraints);

        jdcVencimiento.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jdcVencimiento.setMinimumSize(new java.awt.Dimension(100, 20));
        jdcVencimiento.setPreferredSize(new java.awt.Dimension(200, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 20);
        pnlBot.add(jdcVencimiento, gridBagConstraints);

        jLabel17.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jLabel17.setText("Nueva fecha vencimiento.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        pnlBot.add(jLabel17, gridBagConstraints);

        cmbMes.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        cmbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ENERO", "FEBRERO", "MARZO", "ABRIL", "MAYO", "JUNIO", "JULIO", "AGOSTO", "SEPTIEMBRE", "OCTUBRE", "NOVIEMBRE", "DICIEMBRE" }));
        cmbMes.setMinimumSize(new java.awt.Dimension(150, 20));
        cmbMes.setPreferredSize(new java.awt.Dimension(200, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 20);
        pnlBot.add(cmbMes, gridBagConstraints);

        pnlDerecha.add(pnlBot, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        jPanel3.add(pnlDerecha, gridBagConstraints);

        add(jPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarFechaActionPerformed

        String idPeriodo = listIdPeriodo.get(cmbPeriodo.getSelectedIndex());
        Connection con = ClsConexion.getConection();
        
        String fecha = formatoOriginal.format(jdcVencimiento.getDate());
        String mes = cmbMes.getSelectedItem().toString();
                
        ArrayList<MatriculaEntity> arrayMatricula = matriculaDAL.ListarIdMatricula(idPeriodo, con);
        try {
            
            for(MatriculaEntity me : arrayMatricula) {
            
                if(rbnLonchera.isSelected()) {
                    matriculaDAL.EditarVencimientoLonchera(mes, me.getId_matricula(), fecha, con);
                }
                else if(rbnMensualidad.isSelected()) {
                    matriculaDAL.EditarVencimientoMensualidad(mes, me.getId_matricula(), fecha, con);
                }
            }
            
            ClsConexion.closeConnection(con);
            JOptionPane.showMessageDialog(null, "Fecha de vencimiento editada correctamente","Cambio de fecha vencimiento",JOptionPane.INFORMATION_MESSAGE);
            
        }catch(HeadlessException ex) {
            JOptionPane.showMessageDialog(null, "Error al editar fecha de vencimiento: \n"+ex,"Cambio de fecha vencimiento",JOptionPane.INFORMATION_MESSAGE);
            
        }
        
    }//GEN-LAST:event_btnEditarFechaActionPerformed

    private void cmbNivelItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbNivelItemStateChanged
        
        if(cmbNivel.getSelectedIndex() != -1 ) {
            
            CargarComboPeriodo();             
        }
    }//GEN-LAST:event_cmbNivelItemStateChanged

    private void rbnLoncheraItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbnLoncheraItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnLoncheraItemStateChanged

    private void rbnMensualidadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbnMensualidadItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnMensualidadItemStateChanged

    private void CargarComboNivel() {
        
        ClsNivel niveles = new ClsNivel();
        ArrayList<ClsEntidadNivel> nivele =  niveles.SeleccionarNivel();
        Iterator it = nivele.iterator();
        DefaultComboBoxModel dtm = new DefaultComboBoxModel();
        dtm.removeAllElements();
        cmbNivel.removeAllItems();
                
        while(it.hasNext())
        {
        ClsEntidadNivel Nivel = (ClsEntidadNivel) it.next();       
        listIdNivel.add(Nivel.getNivel_id());
        dtm.addElement(Nivel.getNivel_nombre());                
        }
        cmbNivel.setModel(dtm); 
    }
    
    private void CargarComboPeriodo() {
        
        listIdPeriodo.clear();
        ClsPeriodo periodos = new ClsPeriodo();
        ArrayList<ClsEntidadPeriodo> periodo =  periodos.ListarPeriodo();
        Iterator iterator = periodo.iterator();
        DefaultComboBoxModel DefaultComboBoxModel = new DefaultComboBoxModel();
        DefaultComboBoxModel.removeAllElements();
        cmbPeriodo.removeAllItems();
            
        while(iterator.hasNext())
        {
        ClsEntidadPeriodo Periodo = (ClsEntidadPeriodo) iterator.next();               
        
            if(Periodo.getEstado_Periodo().equals("Activo") &&                     
            listIdNivel.get(cmbNivel.getSelectedIndex()).equals(Periodo.getNivel_Id()))
            {   
            listIdPeriodo.add(Periodo.getId_Periodo());     
            DefaultComboBoxModel.addElement(Periodo.getNombre_Periodo());        
            }
        }
        cmbPeriodo.setModel(DefaultComboBoxModel);       
    }
    
    private int obtenerMesInicioClases(String codMatricula,Connection conx) {
        int mmes;
        String inicioClases = "";
        ClsMatricula matricula = new ClsMatricula();
        ResultSet rsMatricula;    

        try 
        {
            rsMatricula = matricula.SeleccionarMatriculaSolo(codMatricula,conx);
            while(rsMatricula.next())
            {

                inicioClases = rsMatricula.getString("inicio_clases");                    
            }                

        } catch (Exception ex) {
            Logger.getLogger(FrmPagoTodo.class.getName()).log(Level.SEVERE, null, ex);
        }

        mmes = Integer.parseInt(inicioClases.substring(3, 5))-1;
        return mmes;
        }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarFecha;
    private javax.swing.JComboBox<String> cmbMes;
    private javax.swing.JComboBox<String> cmbNivel;
    private javax.swing.JComboBox<String> cmbPeriodo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private com.toedter.calendar.JDateChooser jdcVencimiento;
    private javax.swing.JPanel pnlBot;
    private javax.swing.JPanel pnlDerecha;
    private javax.swing.ButtonGroup rbnGrupo;
    private javax.swing.JRadioButton rbnLonchera;
    private javax.swing.JRadioButton rbnMensualidad;
    // End of variables declaration//GEN-END:variables
}
