/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PckInterfaces;

import java.awt.HeadlessException;
import mpsModel.MatriculaModelo;
import java.awt.Window;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mpsDAL.ItemDAL;
import mpsDAL.ItemStockDAL;
import mpsModel.AlmacenModelo;
import static prymatricula.ClsMisc.fechaActual;

/**
 *
 * @author Kevin
 */
public class AlmacenAdministracionItemAsignar extends javax.swing.JDialog {

    MatriculaModelo matriculaModelo = new MatriculaModelo();
    AlmacenModelo almacenModelo = new AlmacenModelo();
    ArrayList<Object> arrayIdPeriodo = new ArrayList<>();    
    ItemStockDAL itemStockDAL = new ItemStockDAL();
    ItemDAL itemDAL = new ItemDAL();
    int idPeriodo;
    int idAlmacen;
    public AlmacenAdministracionItem almacenAdministracionItem;
    int _IdSeleccionados[];
    String _Nombre[];
    String _Medida[];
    int _Stock[];
    String _Descripcion[];
    String _Tipo[];
            
    /**
     * Creates new form AlmacenAdministracionNuevo
     * @param parentWindow     
     * @param _IdSeleccionados     
     * @param _Nombre     
     * @param _Medida     
     * @param _Stock     
     * @param _Descripcion     
     * @param _Tipo     
     */
    public AlmacenAdministracionItemAsignar
    (
            Window parentWindow, 
            int _IdSeleccionados[], 
            String _Nombre[],
            String _Medida[],
            int _Stock[],
            String _Descripcion[],
            String _Tipo[]
    ){
        super(parentWindow);
        this._IdSeleccionados = _IdSeleccionados; 
        this._Nombre = _Nombre; 
        this._Medida = _Medida; 
        this._Stock = _Stock; 
        this._Descripcion = _Descripcion; 
        this._Tipo = _Tipo;
        
        initComponents();
        
        this.setLocationRelativeTo(parentWindow);
        
        arrayIdPeriodo = matriculaModelo.MostrarComboPeriodos(cmbPeriodo);    
        MostrarAlmacenesPeriodo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlDerecha = new javax.swing.JPanel();
        pnltop = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        pnlbot = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        cmbPeriodo = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlmacenes = new javax.swing.JTable();
        cbxNuevoItem = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(586, 600));
        setPreferredSize(new java.awt.Dimension(586, 646));

        pnlDerecha.setBackground(new java.awt.Color(255, 255, 255));
        pnlDerecha.setMinimumSize(new java.awt.Dimension(586, 414));
        pnlDerecha.setPreferredSize(new java.awt.Dimension(586, 414));
        pnlDerecha.setLayout(new java.awt.BorderLayout());

        pnltop.setBackground(new java.awt.Color(255, 255, 255));
        pnltop.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jLabel3.setText("ASIGNAR ALMACEN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 0);
        pnltop.add(jLabel3, gridBagConstraints);

        jSeparator2.setForeground(new java.awt.Color(224, 224, 224));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 269;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnltop.add(jSeparator2, gridBagConstraints);

        pnlDerecha.add(pnltop, java.awt.BorderLayout.PAGE_START);

        pnlbot.setBackground(new java.awt.Color(255, 255, 255));
        pnlbot.setLayout(new java.awt.GridBagLayout());

        jLabel6.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jLabel6.setText("Periodo.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        pnlbot.add(jLabel6, gridBagConstraints);

        jSeparator3.setForeground(new java.awt.Color(224, 224, 224));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnlbot.add(jSeparator3, gridBagConstraints);

        cmbPeriodo.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        cmbPeriodo.setMinimumSize(new java.awt.Dimension(200, 20));
        cmbPeriodo.setPreferredSize(new java.awt.Dimension(200, 20));
        cmbPeriodo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPeriodoItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 20);
        pnlbot.add(cmbPeriodo, gridBagConstraints);

        btnGuardar.setFont(new java.awt.Font("Droid Sans", 1, 12)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PckIconos/ic_save_black_24dp.png"))); // NOI18N
        btnGuardar.setText("ASIGNAR ALMACEN");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 20);
        pnlbot.add(btnGuardar, gridBagConstraints);

        jScrollPane1.setMinimumSize(new java.awt.Dimension(23, 300));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(452, 420));

        tblAlmacenes.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        tblAlmacenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAlmacenes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAlmacenesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAlmacenes);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        pnlbot.add(jScrollPane1, gridBagConstraints);

        cbxNuevoItem.setBackground(new java.awt.Color(255, 255, 255));
        cbxNuevoItem.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        cbxNuevoItem.setSelected(true);
        cbxNuevoItem.setText("Crear nuevo item y asignar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 20);
        pnlbot.add(cbxNuevoItem, gridBagConstraints);

        pnlDerecha.add(pnlbot, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlDerecha, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbPeriodoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPeriodoItemStateChanged
        
        if(cmbPeriodo.getSelectedIndex() != -1)
        {
            MostrarAlmacenesPeriodo();
        }
        
    }//GEN-LAST:event_cmbPeriodoItemStateChanged

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
        int column = tblAlmacenes.getSelectedColumn();
        int row = tblAlmacenes.getSelectedRow();

        if(row != -1)
        {
            //varios almacenes a la vez
            int FilasAlmacenSeleccionadas[] = tblAlmacenes.getSelectedRows();
            int IdAlmacenSeleccionados[] = new int[FilasAlmacenSeleccionadas.length];
            DefaultTableModel dtmAlmacen = (DefaultTableModel) tblAlmacenes.getModel();
             
            //llena los ID de almacen seleccionados
            if(FilasAlmacenSeleccionadas.length != 0)
            {
                for (int k= 0; k<FilasAlmacenSeleccionadas.length; k++)
                {
                    IdAlmacenSeleccionados[k] = (int)dtmAlmacen.getValueAt(FilasAlmacenSeleccionadas[k], 0);
                }
            }
            
            DefaultTableModel dtmAlmacenes = (DefaultTableModel) tblAlmacenes.getModel();            
            int limiteItem = _IdSeleccionados.length;
            int limiteAlmacen = IdAlmacenSeleccionados.length;
                        
            if(cbxNuevoItem.isSelected()) //Crea un item y lo asigna a un almacen
            {
                try
                {
                    for(int a : IdAlmacenSeleccionados)
                    {
                        for(int i=0; i < limiteItem; i++)
                        {
                            //Crea nuevo registros y asigna almacen
                            int lastId = itemDAL.GuardarItem(_Nombre[i], _Medida[i], _Stock[i], _Descripcion[i],_Tipo[i]);
                            itemDAL.EditarItemAlmacen(lastId, a);
                            itemStockDAL.GuardarItemCantidad(fechaActual(), String.valueOf(_Stock[i]), 
                                    Integer.parseInt(FrmPrincipal.idPersonalLogeado), lastId );
                        }                        
                    }
                    almacenAdministracionItem.MostrarItems();
                    almacenAdministracionItem.LimpiarCampos();
                    
                    this.dispose();
                }
                catch(HeadlessException ex)
                {
                    Logger.getLogger(AlmacenAdministracionItemAsignar.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else //Asigna el item a un almacen
            {

                try
                {
                    for(int a : IdAlmacenSeleccionados)
                    {
                        for(int i=0; i < limiteItem; i++)
                        {
                            itemDAL.EditarItemAlmacen(_IdSeleccionados[i], a);
                        }                         
                    }
                    almacenAdministracionItem.MostrarItems();
                    almacenAdministracionItem.LimpiarCampos();
                    int n = JOptionPane.showConfirmDialog(null, "¿Desea asignar otro almacen?", "Confirmar", JOptionPane.OK_CANCEL_OPTION);
                    if(n == JOptionPane.CANCEL_OPTION) 
                    {
                        this.dispose();
                    } 
                }
                catch(HeadlessException ex)
                {
                    Logger.getLogger(AlmacenAdministracionItemAsignar.class.getName()).log(Level.SEVERE, null, ex);
                }
            }  
        }
        
                         
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tblAlmacenesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAlmacenesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblAlmacenesMouseClicked

    public void FormularioPadre(AlmacenAdministracionItem almacenAdministracionItem)
    {
        this.almacenAdministracionItem = almacenAdministracionItem;
    }
    
    private void MostrarAlmacenesPeriodo()
    {
        idPeriodo = (int) arrayIdPeriodo.get(cmbPeriodo.getSelectedIndex());   
        almacenModelo.MostrarTablaAlmacenAdministracionPeriodo(tblAlmacenes, idPeriodo);
    }
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AlmacenAdministracionNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AlmacenAdministracionNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AlmacenAdministracionNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AlmacenAdministracionNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JCheckBox cbxNuevoItem;
    private javax.swing.JComboBox<String> cmbPeriodo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel pnlDerecha;
    private javax.swing.JPanel pnlbot;
    private javax.swing.JPanel pnltop;
    private javax.swing.JTable tblAlmacenes;
    // End of variables declaration//GEN-END:variables
}
