/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PckInterfaces;

import PckConexion.ClsConexion;
import java.awt.Color;
import java.awt.Window;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;

/**
 *
 * @author Kevin
 */
public class AsistenciaConsultaFichaInasistencia extends javax.swing.JDialog {

    SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
    SimpleDateFormat formatoOriginal = new SimpleDateFormat("yyyy-MM-dd");
    Connection con;
    String idFicha;
    String nombreAlumno;
    
    /**
     * Creates new form AsistenciaConsultaFichaInasistencia
     * @param parentWindow
     * @param idFicha
     * @param nombreAlumno
     */
    public AsistenciaConsultaFichaInasistencia(Window parentWindow, String idFicha, String nombreAlumno) {
        super(parentWindow);
        this.idFicha = idFicha;
        this.nombreAlumno = nombreAlumno;
                        
        initComponents();
        this.setLocationRelativeTo(null);
        
        txtAlumno.setText(nombreAlumno);
        
        LlenarFicha();
        
    }   

    
    private void LlenarFicha()
    {
        con = ClsConexion.getConection();
        PreparedStatement pstmt;
        ResultSet rs;
        String sqlQuery="SELECT inasistencia_ficha_fecha, ina.inasistencia_ficha_motivo, ina.inasistencia_ficha_contacto,\n" +
        "ina.inasistencia_ficha_telefono,ina.inasistencia_ficha_retorno, ina.inasistencia_ficha_justificada\n" +
        "FROM mat_inasistencia_ficha as ina WHERE ina.inasistencia_ficha_id = ?";
        
        try 
        {
            pstmt = con.prepareStatement(sqlQuery);
            pstmt.setString(1, idFicha);
            rs = pstmt.executeQuery();
            
            while(rs.next())
            {   
                txtFechaFicha.setText(formato.format(formatoOriginal.parse(rs.getString("inasistencia_ficha_fecha"))));
                cbxFalta.setSelected(rs.getInt("inasistencia_ficha_justificada") == 1);                
                txtMotivo.setText(rs.getString("inasistencia_ficha_motivo"));
                txtContacto.setText(rs.getString("inasistencia_ficha_contacto"));
                txtTelefono.setText(rs.getString("inasistencia_ficha_telefono"));
                txtFechaRetorno.setText(formato.format(formatoOriginal.parse(rs.getString("inasistencia_ficha_retorno"))));
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(AsistenciaDocenteFichaInasistenciaEditar.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(AsistenciaConsultaFichaInasistencia.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        ClsConexion.closeConnection(con);
    }
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        pnltop = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        pnlbot = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        txtAlumno = new javax.swing.JLabel();
        txtMotivo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtContacto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cbxFalta = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        txtFechaFicha = new javax.swing.JTextField();
        txtFechaRetorno = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        pnltop.setBackground(new java.awt.Color(255, 255, 255));
        pnltop.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jLabel3.setText("FICHA INASISTENCIA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 0);
        pnltop.add(jLabel3, gridBagConstraints);

        jSeparator2.setForeground(new java.awt.Color(224, 224, 224));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 269;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        pnltop.add(jSeparator2, gridBagConstraints);

        jPanel1.add(pnltop, java.awt.BorderLayout.PAGE_START);

        pnlbot.setBackground(new java.awt.Color(255, 255, 255));
        pnlbot.setLayout(new java.awt.GridBagLayout());

        jLabel7.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jLabel7.setText("Telefono contacto.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        pnlbot.add(jLabel7, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jLabel8.setText("Persona contacto.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        pnlbot.add(jLabel8, gridBagConstraints);

        txtTelefono.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        txtTelefono.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtTelefono.setEnabled(false);
        txtTelefono.setMinimumSize(new java.awt.Dimension(400, 20));
        txtTelefono.setPreferredSize(new java.awt.Dimension(400, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 0, 20);
        pnlbot.add(txtTelefono, gridBagConstraints);

        txtAlumno.setFont(new java.awt.Font("Droid Sans", 1, 12)); // NOI18N
        txtAlumno.setText("Alumno.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 20);
        pnlbot.add(txtAlumno, gridBagConstraints);

        txtMotivo.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        txtMotivo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtMotivo.setEnabled(false);
        txtMotivo.setMinimumSize(new java.awt.Dimension(450, 20));
        txtMotivo.setPreferredSize(new java.awt.Dimension(450, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 0, 20);
        pnlbot.add(txtMotivo, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jLabel10.setText("Fecha retorno.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        pnlbot.add(jLabel10, gridBagConstraints);

        txtContacto.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        txtContacto.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtContacto.setEnabled(false);
        txtContacto.setMinimumSize(new java.awt.Dimension(200, 20));
        txtContacto.setPreferredSize(new java.awt.Dimension(250, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 0, 20);
        pnlbot.add(txtContacto, gridBagConstraints);

        jLabel11.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jLabel11.setText("Motivo inasistencia.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        pnlbot.add(jLabel11, gridBagConstraints);

        cbxFalta.setBackground(new java.awt.Color(255, 255, 255));
        cbxFalta.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        cbxFalta.setText("Falta justificada.");
        cbxFalta.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 20);
        pnlbot.add(cbxFalta, gridBagConstraints);

        jLabel12.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jLabel12.setText("Fecha ficha.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        pnlbot.add(jLabel12, gridBagConstraints);

        txtFechaFicha.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        txtFechaFicha.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtFechaFicha.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 0, 20);
        pnlbot.add(txtFechaFicha, gridBagConstraints);

        txtFechaRetorno.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        txtFechaRetorno.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtFechaRetorno.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 20, 20);
        pnlbot.add(txtFechaRetorno, gridBagConstraints);

        jPanel1.add(pnlbot, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbxFalta;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel pnlbot;
    private javax.swing.JPanel pnltop;
    private javax.swing.JLabel txtAlumno;
    private javax.swing.JTextField txtContacto;
    private javax.swing.JTextField txtFechaFicha;
    private javax.swing.JTextField txtFechaRetorno;
    private javax.swing.JTextField txtMotivo;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
