/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PckInterfaces;

import PckConexion.ClsConexion;
import PckEntidad.ClsEntidadEgresoReporte;
import PckEntidad.ClsEntidadIngEgre;
import PckNegocio.ClsIngresosEgresos;
import java.awt.print.PageFormat;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.PrintService;
import javax.print.PrintServiceLookup;
import javax.print.attribute.AttributeSet;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.HashPrintServiceAttributeSet;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.print.attribute.standard.Copies;
import javax.print.attribute.standard.MediaSizeName;
import javax.print.attribute.standard.PrinterName;
import mpsModel.PagoModelo;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRExporterParameter;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.export.JRPrintServiceExporter;
import net.sf.jasperreports.engine.export.JRPrintServiceExporterParameter;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import prymatricula.ClsMisc;

/**
 *
 * @author Kevin
 */
public class ContabilidadIngresosEgresos extends javax.swing.JPanel {

    
    PagoModelo pagoModelo = new PagoModelo();
    
   
    private boolean firstRun = false;
    
    /**
     * Creates new form AsistenciaConsulta
     */
    public ContabilidadIngresosEgresos() {
        initComponents();
        
        Date dateNow = ClsMisc.ObtenerFechaActual();
        jdcFechaCajaIngresos.setDate(dateNow);        
        jdcFechaBanco.setDate(dateNow);
        
        firstRun = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlBot = new javax.swing.JPanel();
        tbpAsistencia = new javax.swing.JTabbedPane();
        pnlIngresosCaja = new javax.swing.JPanel();
        pnltop2 = new javax.swing.JPanel();
        jdcFechaCajaIngresos = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        pnlMid1 = new javax.swing.JPanel();
        pnlFicha1 = new javax.swing.JPanel();
        txtIngresosCajaTotal = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblIngresosCaja = new javax.swing.JTable();
        pnlEgresosCaja = new javax.swing.JPanel();
        pnltop4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        txtFechaEgresoCaja = new javax.swing.JTextField();
        pnlMid3 = new javax.swing.JPanel();
        pnlFicha3 = new javax.swing.JPanel();
        txtCierreCaja = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtEgresosCajaTotal = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblEgresosCaja = new javax.swing.JTable();
        pnlBotEgresos = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        btnReporteIngresosEgresos = new javax.swing.JButton();
        pnlIngresosBanco = new javax.swing.JPanel();
        pnltop3 = new javax.swing.JPanel();
        jdcFechaBanco = new com.toedter.calendar.JDateChooser();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        pnlMid2 = new javax.swing.JPanel();
        pnlFicha2 = new javax.swing.JPanel();
        txtIngresosBanco = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblIngresosBanco = new javax.swing.JTable();
        pnlBotIngresosBanco = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        btnReporteIngresosBanco = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(237, 240, 242));
        jPanel4.setPreferredSize(new java.awt.Dimension(911, 50));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jPanel5.setBackground(new java.awt.Color(237, 240, 242));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Droid Sans", 1, 12)); // NOI18N
        jLabel1.setText("INGRESOS - EGRESOS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        jPanel5.add(jLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        jPanel4.add(jPanel5, gridBagConstraints);

        add(jPanel4, java.awt.BorderLayout.PAGE_START);

        pnlBot.setBackground(new java.awt.Color(237, 240, 242));
        pnlBot.setLayout(new java.awt.GridBagLayout());

        tbpAsistencia.setFont(new java.awt.Font("Droid Sans", 0, 12)); // NOI18N

        pnlIngresosCaja.setBackground(new java.awt.Color(255, 255, 255));
        pnlIngresosCaja.setLayout(new java.awt.BorderLayout());

        pnltop2.setBackground(new java.awt.Color(255, 255, 255));
        pnltop2.setLayout(new java.awt.GridBagLayout());

        jdcFechaCajaIngresos.setDateFormatString("dd/MM/yyyy");
        jdcFechaCajaIngresos.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jdcFechaCajaIngresos.setMinimumSize(new java.awt.Dimension(50, 23));
        jdcFechaCajaIngresos.setPreferredSize(new java.awt.Dimension(150, 22));
        jdcFechaCajaIngresos.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jdcFechaCajaIngresosPropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        pnltop2.add(jdcFechaCajaIngresos, gridBagConstraints);

        jLabel16.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jLabel16.setText("Fecha.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        pnltop2.add(jLabel16, gridBagConstraints);

        pnlIngresosCaja.add(pnltop2, java.awt.BorderLayout.PAGE_START);

        pnlMid1.setBackground(new java.awt.Color(255, 255, 255));
        pnlMid1.setLayout(new java.awt.GridBagLayout());

        pnlFicha1.setBackground(new java.awt.Color(255, 255, 255));
        pnlFicha1.setLayout(new java.awt.GridBagLayout());

        txtIngresosCajaTotal.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        txtIngresosCajaTotal.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtIngresosCajaTotal.setEnabled(false);
        txtIngresosCajaTotal.setMinimumSize(new java.awt.Dimension(120, 20));
        txtIngresosCajaTotal.setPreferredSize(new java.awt.Dimension(120, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        pnlFicha1.add(txtIngresosCajaTotal, gridBagConstraints);

        jLabel20.setFont(new java.awt.Font("Droid Sans", 1, 14)); // NOI18N
        jLabel20.setText("TOTAL INGRESOS CAJA:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        pnlFicha1.add(jLabel20, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 20, 20);
        pnlMid1.add(pnlFicha1, gridBagConstraints);

        tblIngresosCaja.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        tblIngresosCaja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblIngresosCaja.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(tblIngresosCaja);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        pnlMid1.add(jScrollPane4, gridBagConstraints);

        pnlIngresosCaja.add(pnlMid1, java.awt.BorderLayout.CENTER);

        tbpAsistencia.addTab("Ingresos caja", pnlIngresosCaja);

        pnlEgresosCaja.setBackground(new java.awt.Color(255, 255, 255));
        pnlEgresosCaja.setLayout(new java.awt.BorderLayout());

        pnltop4.setBackground(new java.awt.Color(255, 255, 255));
        pnltop4.setLayout(new java.awt.GridBagLayout());

        jLabel18.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jLabel18.setText("Fecha.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        pnltop4.add(jLabel18, gridBagConstraints);

        txtFechaEgresoCaja.setFont(new java.awt.Font("Droid Sans", 0, 12)); // NOI18N
        txtFechaEgresoCaja.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txtFechaEgresoCaja.setEnabled(false);
        txtFechaEgresoCaja.setMinimumSize(new java.awt.Dimension(150, 20));
        txtFechaEgresoCaja.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        pnltop4.add(txtFechaEgresoCaja, gridBagConstraints);

        pnlEgresosCaja.add(pnltop4, java.awt.BorderLayout.PAGE_START);

        pnlMid3.setBackground(new java.awt.Color(255, 255, 255));
        pnlMid3.setLayout(new java.awt.GridBagLayout());

        pnlFicha3.setBackground(new java.awt.Color(255, 255, 255));
        pnlFicha3.setLayout(new java.awt.GridBagLayout());

        txtCierreCaja.setFont(new java.awt.Font("Droid Sans", 1, 14)); // NOI18N
        txtCierreCaja.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCierreCaja.setEnabled(false);
        txtCierreCaja.setMinimumSize(new java.awt.Dimension(120, 20));
        txtCierreCaja.setPreferredSize(new java.awt.Dimension(120, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 0, 0);
        pnlFicha3.add(txtCierreCaja, gridBagConstraints);

        jLabel22.setFont(new java.awt.Font("Droid Sans", 1, 14)); // NOI18N
        jLabel22.setText("TOTAL CIERRE CAJA:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        pnlFicha3.add(jLabel22, gridBagConstraints);

        jLabel23.setFont(new java.awt.Font("Droid Sans", 1, 14)); // NOI18N
        jLabel23.setText("TOTAL EGRESOS CAJA:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        pnlFicha3.add(jLabel23, gridBagConstraints);

        txtEgresosCajaTotal.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        txtEgresosCajaTotal.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtEgresosCajaTotal.setEnabled(false);
        txtEgresosCajaTotal.setMinimumSize(new java.awt.Dimension(120, 20));
        txtEgresosCajaTotal.setPreferredSize(new java.awt.Dimension(120, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        pnlFicha3.add(txtEgresosCajaTotal, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 20, 20);
        pnlMid3.add(pnlFicha3, gridBagConstraints);

        tblEgresosCaja.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        tblEgresosCaja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEgresosCaja.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane5.setViewportView(tblEgresosCaja);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        pnlMid3.add(jScrollPane5, gridBagConstraints);

        pnlEgresosCaja.add(pnlMid3, java.awt.BorderLayout.CENTER);

        pnlBotEgresos.setBackground(new java.awt.Color(255, 255, 255));
        pnlBotEgresos.setLayout(new java.awt.GridBagLayout());

        jSeparator1.setBackground(new java.awt.Color(224, 224, 224));
        jSeparator1.setForeground(new java.awt.Color(224, 224, 224));
        jSeparator1.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 20);
        pnlBotEgresos.add(jSeparator1, gridBagConstraints);

        btnReporteIngresosEgresos.setFont(new java.awt.Font("Droid Sans", 1, 14)); // NOI18N
        btnReporteIngresosEgresos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PckIconos/ic_assignment_black_24dp.png"))); // NOI18N
        btnReporteIngresosEgresos.setText("GENERAR REPORTE");
        btnReporteIngresosEgresos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnReporteIngresosEgresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteIngresosEgresosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 20);
        pnlBotEgresos.add(btnReporteIngresosEgresos, gridBagConstraints);

        pnlEgresosCaja.add(pnlBotEgresos, java.awt.BorderLayout.PAGE_END);

        tbpAsistencia.addTab("Egresos caja", pnlEgresosCaja);

        pnlIngresosBanco.setBackground(new java.awt.Color(255, 255, 255));
        pnlIngresosBanco.setLayout(new java.awt.BorderLayout());

        pnltop3.setBackground(new java.awt.Color(255, 255, 255));
        pnltop3.setLayout(new java.awt.GridBagLayout());

        jdcFechaBanco.setDateFormatString("dd/MM/yyyy");
        jdcFechaBanco.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jdcFechaBanco.setMinimumSize(new java.awt.Dimension(50, 23));
        jdcFechaBanco.setPreferredSize(new java.awt.Dimension(150, 22));
        jdcFechaBanco.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jdcFechaBancoPropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 10, 0);
        pnltop3.add(jdcFechaBanco, gridBagConstraints);

        jSeparator4.setBackground(new java.awt.Color(237, 240, 242));
        jSeparator4.setForeground(new java.awt.Color(237, 240, 242));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        pnltop3.add(jSeparator4, gridBagConstraints);

        jLabel17.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jLabel17.setText("Fecha.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 10, 0);
        pnltop3.add(jLabel17, gridBagConstraints);

        pnlIngresosBanco.add(pnltop3, java.awt.BorderLayout.PAGE_START);

        pnlMid2.setBackground(new java.awt.Color(255, 255, 255));
        pnlMid2.setLayout(new java.awt.GridBagLayout());

        pnlFicha2.setBackground(new java.awt.Color(255, 255, 255));
        pnlFicha2.setLayout(new java.awt.GridBagLayout());

        txtIngresosBanco.setFont(new java.awt.Font("Droid Sans", 0, 14)); // NOI18N
        txtIngresosBanco.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtIngresosBanco.setEnabled(false);
        txtIngresosBanco.setMinimumSize(new java.awt.Dimension(200, 20));
        txtIngresosBanco.setPreferredSize(new java.awt.Dimension(250, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        pnlFicha2.add(txtIngresosBanco, gridBagConstraints);

        jLabel21.setFont(new java.awt.Font("Droid Sans", 1, 14)); // NOI18N
        jLabel21.setText("TOTAL INGRESOS POR BANCO:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        pnlFicha2.add(jLabel21, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 20, 20);
        pnlMid2.add(pnlFicha2, gridBagConstraints);

        tblIngresosBanco.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        tblIngresosBanco.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblIngresosBanco.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane7.setViewportView(tblIngresosBanco);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        pnlMid2.add(jScrollPane7, gridBagConstraints);

        pnlIngresosBanco.add(pnlMid2, java.awt.BorderLayout.CENTER);

        pnlBotIngresosBanco.setBackground(new java.awt.Color(255, 255, 255));
        pnlBotIngresosBanco.setLayout(new java.awt.GridBagLayout());

        jSeparator2.setBackground(new java.awt.Color(224, 224, 224));
        jSeparator2.setForeground(new java.awt.Color(224, 224, 224));
        jSeparator2.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 20);
        pnlBotIngresosBanco.add(jSeparator2, gridBagConstraints);

        btnReporteIngresosBanco.setFont(new java.awt.Font("Droid Sans", 1, 14)); // NOI18N
        btnReporteIngresosBanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PckIconos/ic_assignment_black_24dp.png"))); // NOI18N
        btnReporteIngresosBanco.setText("GENERAR REPORTE");
        btnReporteIngresosBanco.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnReporteIngresosBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteIngresosBancoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 20);
        pnlBotIngresosBanco.add(btnReporteIngresosBanco, gridBagConstraints);

        pnlIngresosBanco.add(pnlBotIngresosBanco, java.awt.BorderLayout.PAGE_END);

        tbpAsistencia.addTab("Ingresos banco", pnlIngresosBanco);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        pnlBot.add(tbpAsistencia, gridBagConstraints);

        add(pnlBot, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jdcFechaCajaIngresosPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jdcFechaCajaIngresosPropertyChange
        
        if(firstRun) {
            
            if(jdcFechaCajaIngresos.getDate() != null) {
                
                try( Connection con = ClsConexion.getConection() ) {
                    
                    Date datePicked = jdcFechaCajaIngresos.getDate();
                    java.sql.Date datePickedSQL = new java.sql.Date(datePicked.getTime());
                    txtFechaEgresoCaja.setText(ClsMisc.formatoFecha(datePicked));
                    CargarTablaIngresosCaja(datePickedSQL, con);
                    CargarTablaEgresosCaja(datePickedSQL, con);
                    CalcularCierreCaja();
                    
                } catch (SQLException ex) {
                    Logger.getLogger(ContabilidadIngresosEgresos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
                    
        }
    }//GEN-LAST:event_jdcFechaCajaIngresosPropertyChange

    private void jdcFechaBancoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jdcFechaBancoPropertyChange
        
        if(firstRun) {
            
            if(jdcFechaBanco.getDate() != null) {
                
                try( Connection con = ClsConexion.getConection() ) {
                    
                    Date datePicked = jdcFechaBanco.getDate();
                    java.sql.Date datePickedSQL = new java.sql.Date(datePicked.getTime());                    
                    CargarTablaIngresosBanco(datePickedSQL, con);
                    
                } catch (SQLException ex) {
                    Logger.getLogger(ContabilidadIngresosEgresos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
                    
        }
    }//GEN-LAST:event_jdcFechaBancoPropertyChange

    private void btnReporteIngresosEgresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteIngresosEgresosActionPerformed
        
        try( Connection con = ClsConexion.getConection()) {
            
            GenerarReporteCierreCaja(con);
            
        } catch (SQLException ex) {
            Logger.getLogger(ContabilidadIngresosEgresos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnReporteIngresosEgresosActionPerformed

    private void btnReporteIngresosBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteIngresosBancoActionPerformed
        
        try( Connection con = ClsConexion.getConection()) {
            
            Date datePicked = jdcFechaBanco.getDate();
            java.sql.Date datePickedSQL = new java.sql.Date(datePicked.getTime());
            GenerarReporteIngresosBanco(datePickedSQL,con);
            
        } catch (SQLException ex) {
            Logger.getLogger(ContabilidadIngresosEgresos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnReporteIngresosBancoActionPerformed

    private void CargarTablaIngresosBanco(java.sql.Date datePickedSQL, Connection con) {
        
        String ingresosBanco = String.valueOf(pagoModelo.CargarTablaIngresosBanco(tblIngresosBanco, datePickedSQL, con));
        txtIngresosBanco.setText(ingresosBanco);
    }
    
    private void CargarTablaIngresosCaja(java.sql.Date datePickedSQL, Connection con) {
        
        String ingresosCaja = String.valueOf(pagoModelo.CargarTablaIngresosCaja(tblIngresosCaja, datePickedSQL, con));
        txtIngresosCajaTotal.setText(ingresosCaja);          
    }
    
    private void CargarTablaEgresosCaja(java.sql.Date datePickedSQL, Connection con) {
        
        String egresosCaja = String.valueOf(pagoModelo.CargarTablaEgresosCaja(tblEgresosCaja, datePickedSQL, con));
        txtEgresosCajaTotal.setText(egresosCaja);
    }
        
    private void CalcularCierreCaja() {
        
        Double ingresosCaja = Double.parseDouble(txtIngresosCajaTotal.getText());
        Double egresosCaja = Double.parseDouble(txtEgresosCajaTotal.getText());
        pagoModelo.CargarCierreCaja(txtCierreCaja, ingresosCaja, egresosCaja);
    }
    
    private void GenerarReporteIngresosBanco(java.sql.Date datePickedSQL, Connection con) {
        
        pagoModelo.GenerarReporteIngresosBanco(datePickedSQL, con);
    }
    
    private void GenerarReporteCierreCaja(Connection con) {
        
        //REPORTE DE DOS TABLAS//
        //variables generales
        double auxi=0.0;
        double auxe=0.0;
        double total=0.0;
        String fecha = ClsMisc.formatoFecha(jdcFechaCajaIngresos.getDate());
        ClsIngresosEgresos cie = new ClsIngresosEgresos();
       
        //REPORTE FINALLLLL  
        //Los dataSource se pueden enviar como parametros, declarandolos como tipo LIST,
        //luego obtener los sbreportes indicando de donde obtendran sus debidos datasource
        //asi:  new net.sf.jasperreports.engine.data.JRBeanCollectionDataSource($P{SUB_DATA_SOURCE})
      
        //1 Obtenemos los dataSource que utilizaremos en los reportes
        ArrayList<ClsEntidadIngEgre> dataBean ;        
        con = ClsConexion.getConection();
        dataBean = cie.SeleccionarIngresos(fecha,con);    
        for(ClsEntidadIngEgre i: dataBean)
        { 
            if(!i.Tipo.equals("anulada")) 
            {
                auxi = auxi + Double.parseDouble(i.Monto);
            }                
        } 
        ClsConexion.closeConnection(con);
        con = ClsConexion.getConection();
        ArrayList<ClsEntidadEgresoReporte> dataBean2;        
        dataBean2 = cie.SeleccionarEgresoReporte(fecha,con);
        for(ClsEntidadEgresoReporte i: dataBean2)
        { 
          auxe = auxe + Double.parseDouble(i.monto);
        }
        
        total = auxi-auxe;
        ClsConexion.closeConnection(con);
        //2 COMPILAMOS LOS SUBREPORTS CON EL REPORTE PRINCIPAL
        try {            
            String  url7 ="/Reportes/RptCierreCaja.jrxml";
            //principal
            JasperDesign jasperDesign = JRXmlLoader.load(System.getProperty("user.dir")+url7);
            JasperReport ReportMain = JasperCompileManager.compileReport(jasperDesign);
            System.out.print(System.getProperty("user.dir"));

            Map<String, Object> params = new HashMap();
            params.put("auxi",String.valueOf(auxi));
            params.put("auxe",String.valueOf(auxe));
            params.put("total",String.valueOf(total));
            params.put("dsreport1", dataBean);
            params.put("dsreport2", dataBean2);
            params.put("fecha", fecha);
            params.put("SUBREPORT_DIR", System.getProperty("user.dir")+"\\Reportes\\");
            JRBeanCollectionDataSource ds2 = new JRBeanCollectionDataSource(null);
            JasperPrint print = JasperFillManager.fillReport(ReportMain, params, ds2); 
            
            PrinterJob printerJob = PrinterJob.getPrinterJob();
            PageFormat pageFormat = PrinterJob.getPrinterJob().defaultPage();
            printerJob.defaultPage(pageFormat);

            int selectedService = 0;

            AttributeSet attributeSet = new HashPrintServiceAttributeSet(new PrinterName("WebPrintService", null));

            PrintService[] printService = PrintServiceLookup.lookupPrintServices(null, attributeSet);

             try {
                printerJob.setPrintService(printService[selectedService]);

            } catch (PrinterException e) {

                System.out.println(e);
            }
            JRPrintServiceExporter exporter;
            PrintRequestAttributeSet printRequestAttributeSet = new HashPrintRequestAttributeSet();
            printRequestAttributeSet.add(MediaSizeName.NA_LETTER);
            printRequestAttributeSet.add(new Copies(1));

            // these are deprecated
            exporter = new JRPrintServiceExporter();
            exporter.setParameter(JRExporterParameter.JASPER_PRINT, print);
            exporter.setParameter(JRPrintServiceExporterParameter.PRINT_SERVICE, printService[selectedService]);
            exporter.setParameter(JRPrintServiceExporterParameter.PRINT_SERVICE_ATTRIBUTE_SET, printService[selectedService].getAttributes());
            exporter.setParameter(JRPrintServiceExporterParameter.PRINT_REQUEST_ATTRIBUTE_SET, printRequestAttributeSet);
            exporter.setParameter(JRPrintServiceExporterParameter.DISPLAY_PAGE_DIALOG, Boolean.FALSE);
            exporter.setParameter(JRPrintServiceExporterParameter.DISPLAY_PRINT_DIALOG, Boolean.FALSE);
            exporter.exportReport();
            
            
            
//            JasperViewer view = new JasperViewer(print,false);
//            view.setTitle("Cierre de Caja");
//            view.setVisible(true);            
            
        } catch (JRException ex) {
            Logger.getLogger(FrmIngresosEgresos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReporteIngresosBanco;
    private javax.swing.JButton btnReporteIngresosEgresos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private com.toedter.calendar.JDateChooser jdcFechaBanco;
    private com.toedter.calendar.JDateChooser jdcFechaCajaIngresos;
    private javax.swing.JPanel pnlBot;
    private javax.swing.JPanel pnlBotEgresos;
    private javax.swing.JPanel pnlBotIngresosBanco;
    private javax.swing.JPanel pnlEgresosCaja;
    private javax.swing.JPanel pnlFicha1;
    private javax.swing.JPanel pnlFicha2;
    private javax.swing.JPanel pnlFicha3;
    private javax.swing.JPanel pnlIngresosBanco;
    private javax.swing.JPanel pnlIngresosCaja;
    private javax.swing.JPanel pnlMid1;
    private javax.swing.JPanel pnlMid2;
    private javax.swing.JPanel pnlMid3;
    private javax.swing.JPanel pnltop2;
    private javax.swing.JPanel pnltop3;
    private javax.swing.JPanel pnltop4;
    private javax.swing.JTable tblEgresosCaja;
    private javax.swing.JTable tblIngresosBanco;
    private javax.swing.JTable tblIngresosCaja;
    private javax.swing.JTabbedPane tbpAsistencia;
    private javax.swing.JTextField txtCierreCaja;
    private javax.swing.JTextField txtEgresosCajaTotal;
    private javax.swing.JTextField txtFechaEgresoCaja;
    private javax.swing.JTextField txtIngresosBanco;
    private javax.swing.JTextField txtIngresosCajaTotal;
    // End of variables declaration//GEN-END:variables
}
