/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PckInterfaces;

import ClsEntidadReporte.ClsEntidadDescuento;
import PckConexion.ClsConexion;
import PckEntidad.ClsEntidadNivel;
import PckEntidad.ClsEntidadPeriodo;
import PckNegocio.ClsNivel;
import PckNegocio.ClsPeriodo;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.DefaultComboBoxModel;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;

/**
 *
 * @author John Kevin Montes De Oca Vizcarra
 * @email jkevin.mv@gmail.com
 */
public class FrmAlumnosDescuento extends javax.swing.JInternalFrame {

    private static final String LOGOTIPO = System.getProperty("user.dir")+"/Img/solr.jpg";
    ArrayList<String> codigoNivel = new ArrayList();
    ArrayList<String> codigoPeriodo = new ArrayList();
    String idPeriodo = "0";
    
    /**
     * Creates new form FrmAlumnosDescuento
     */
    public FrmAlumnosDescuento() {
        initComponents();
        cargarComboNivel();
        cargarComboPeriodo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        cmbNivel = new javax.swing.JComboBox();
        cmbPeriodo = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnGenerar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setTitle("Alumnos con Descuento");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtro"));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbNivel.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        cmbNivel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "GUARDERIA", "INICIAL" }));
        cmbNivel.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbNivelItemStateChanged(evt);
            }
        });
        jPanel7.add(cmbNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 250, -1));

        cmbPeriodo.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        cmbPeriodo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel7.add(cmbPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 250, -1));

        jLabel1.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jLabel1.setText("Nivel:");
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 20));

        jLabel2.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jLabel2.setText("Periodo:");
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 20));

        btnGenerar.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        btnGenerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PckIconos/process.png"))); // NOI18N
        btnGenerar.setText("Generar Reporte");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PckIconos/ic_exit_to_app_black_24dp.png"))); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(397, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGenerar, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                .addContainerGap(197, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbNivelItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbNivelItemStateChanged

        if(cmbNivel.getSelectedIndex() != -1)
        {
            cargarComboPeriodo();
        }

    }//GEN-LAST:event_cmbNivelItemStateChanged

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
       
        //AULA //ALUMNO // MOTIVO //DEBERIA PAGAR // PAGA //DIFERENCIA
        ClsPeriodo clsPeriodo;
        ClsEntidadDescuento clsEntidadDescuento;
        Connection con = null;
        Double total = 0.0;        
        ArrayList<ClsEntidadDescuento> arrayDescuento = new ArrayList<>();
        ResultSet rsPeriodo;
        Map mapa;
        JasperPrint jPrint;
        JasperViewer jView;
        String rJrxml = "/Reportes/RptDescuento.jrxml";
        String rJasper = "/Reportes/RptDescuento.jasper";
        
        idPeriodo = codigoPeriodo.get(cmbPeriodo.getSelectedIndex());
        clsPeriodo = new ClsPeriodo();
                
        try 
        {
            con = ClsConexion.getConection();
            rsPeriodo = clsPeriodo.ListarAlumnosDescuento(con, idPeriodo);
            while(rsPeriodo.next())
            {
                System.out.println("id: "+rsPeriodo.getString("idmat"));
                clsEntidadDescuento = new ClsEntidadDescuento(
                            rsPeriodo.getString("nombre_seccion"), 
                            rsPeriodo.getString("alumno"),
                            rsPeriodo.getString("motivo"), 
                            rsPeriodo.getString("mensualidad"), 
                            rsPeriodo.getString("paga"), 
                            rsPeriodo.getString("diferencia")
                        );
                arrayDescuento.add(clsEntidadDescuento);
                if(rsPeriodo.getString("diferencia").equals(""))
                {
                    total = total + 0.0;
                }
                else
                {
                    total = total + Double.parseDouble(rsPeriodo.getString("diferencia"));  
                }
                
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(FrmAlumnosDescuento.class.getName()).log(Level.SEVERE, null, ex);
            ClsConexion.closeConnection(con);
        }
        finally
        {
            ClsConexion.closeConnection(con);
        }
        
        try 
        {
            mapa = new HashMap();
            mapa.put("total", String.valueOf(total));            
            mapa.put("logo", LOGOTIPO);
            mapa.put("periodo", cmbPeriodo.getSelectedItem().toString());
            
            JRBeanCollectionDataSource ds = new JRBeanCollectionDataSource(arrayDescuento);
            //JasperCompileManager.compileReportToFile(System.getProperty("user.dir") + rJrxml, System.getProperty("user.dir") + rJasper);
            JasperDesign jasperDesign = JRXmlLoader.load(System.getProperty("user.dir") + rJrxml);
            JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
            jPrint = JasperFillManager.fillReport(jasperReport, mapa, ds);
            jView = new JasperViewer(jPrint, false);
            jView.setTitle("Reporte Alumnos con Descuento");
            jView.setVisible(true);
            
        } catch (JRException ex) {
            Logger.getLogger(FrmRptSexoAlumno.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void cargarComboNivel()
    {
        ClsNivel nivel = new ClsNivel();
        ArrayList<ClsEntidadNivel> arrayNivel =  nivel.SeleccionarNivel();        
        DefaultComboBoxModel dtm = new DefaultComboBoxModel();
        dtm.removeAllElements();
        cmbNivel.removeAllItems();
        for(ClsEntidadNivel n : arrayNivel)
        {            
            codigoNivel.add(n.getNivel_id());            
            dtm.addElement(n.getNivel_nombre()); 
        }
        cmbNivel.setModel(dtm); 
    }
    
    private void cargarComboPeriodo()
    {
        codigoPeriodo.clear();
        ClsPeriodo clsPeriodo = new ClsPeriodo();
        ArrayList<ClsEntidadPeriodo> arrayPeriodo =  clsPeriodo.ListarPeriodo();        
        DefaultComboBoxModel dcm = new DefaultComboBoxModel();
        dcm.removeAllElements();
        cmbPeriodo.removeAllItems();
        int nivelIndex=0;
        nivelIndex = cmbNivel.getSelectedIndex();
        for(ClsEntidadPeriodo p : arrayPeriodo)
        {            
            if(p.getEstado_Periodo().equals("Activo") && codigoNivel.get(nivelIndex).equals(p.getNivel_Id()))
            {
                codigoPeriodo.add(p.getId_Periodo());
                dcm.addElement(p.getNombre_Periodo());
            }
        }
        cmbPeriodo.setModel(dcm);       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerar;
    private javax.swing.JComboBox cmbNivel;
    private javax.swing.JComboBox cmbPeriodo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
}
