/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PckInterfaces;

import PckConexion.ClsConexion;
import PckEntidad.ClsEntidadEntregable;
import PckEntidad.ClsEntidadPeriodo;
import PckEntidad.ClsEntidadSeccion;
import PckEntidad.ClsEntidadSubEntregable;
import PckNegocio.ClsEntregable;
import PckNegocio.ClsMatMen;
import PckNegocio.ClsPeriodo;
import PckNegocio.ClsRaices;
import PckNegocio.ClsSeccion;
import PckNegocio.ClsSubEntregable;
import java.awt.Desktop;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import prymatricula.ClsMisc;
import static prymatricula.ClsMisc.obtenerMeses;
import prymatricula.JTreeFile;

/**
 *
 * @author Kevin
 */
public class FrmEntregables extends javax.swing.JInternalFrame {
    private String ruta;
    private String rutaFormato;
    ArrayList<String> Entregable = new ArrayList();
    ArrayList<String> codigoPeriodo = new ArrayList();
    DefaultListModel dlm = new DefaultListModel();
    Connection con;
    /**
     * Creates new form FrmEntregables
     */
    public FrmEntregables() {
        initComponents();
        ruta = cargarRaiz();
         System.out.println(ruta);
        txtRaiz.setText(ruta);
        
        if(cargarRaiz()!=null)
        {            
            File aux = new File(ruta);   
            System.out.println(aux.getName()+" "+ruta);
            actualizarArbol(aux.getName(),ruta);
        }
        
        rutaFormato = cargarRaizFormato();
        txtRaizFormato.setText(rutaFormato);
        if(cargarRaizFormato()!=null)
        {            
            File aux = new File(rutaFormato);   
            System.out.println(aux.getName()+" "+rutaFormato);
            actualizarArbolFormato(aux.getName(),rutaFormato);
        }
        
        cargarComboPeriodo();
        cargaEntregable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        cmbPeriodo = new javax.swing.JComboBox();
        lblPeriodo1 = new javax.swing.JLabel();
        btnQuitarEstructura = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        treEstructura = new javax.swing.JTree();
        jButton3 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        txtRaiz = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnRaiz = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtEntregable = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstEntregable = new javax.swing.JList<>();
        btnAgregar = new javax.swing.JButton();
        btnQuitar = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        btnGuardarRaiz = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnAbrirRaiz = new javax.swing.JButton();
        btnGenerar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        txtRaizFormato = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnRaizFormato = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        treFormato = new javax.swing.JTree();
        jButton4 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        btnGuardarRaizFormato = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnAbrirRaizFormato = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Administrar Directorios");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Agregar entregables a"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbPeriodo.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        cmbPeriodo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2014-I", "INICIAL-2014" }));
        jPanel4.add(cmbPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 190, -1));

        lblPeriodo1.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        lblPeriodo1.setText("Periodo:");
        jPanel4.add(lblPeriodo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 20));

        btnQuitarEstructura.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        btnQuitarEstructura.setForeground(new java.awt.Color(255, 0, 0));
        btnQuitarEstructura.setText("<html> <p align=center>Quitar Estructura</p> <p align=center>en BD</p> </html>");
        btnQuitarEstructura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarEstructuraActionPerformed(evt);
            }
        });
        jPanel4.add(btnQuitarEstructura, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 120, 40));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 470, 90));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Estructura"));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        treEstructura.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        treEstructura.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(treEstructura);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 270, 340));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PckIcoMenu/refresh.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 30, 20));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 320, 390));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Carpeta raíz"));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtRaiz.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jPanel7.add(txtRaiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 210, -1));

        jLabel3.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jLabel3.setText("Carpeta donde se almacenarán entregables:");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        btnRaiz.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        btnRaiz.setText("...");
        btnRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaizActionPerformed(evt);
            }
        });
        jPanel7.add(btnRaiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 40, 20));

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 320, 100));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Entregables"));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jLabel1.setText("Nombre Entregable:");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        txtEntregable.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jPanel6.add(txtEntregable, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 250, -1));

        lstEntregable.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        lstEntregable.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstEntregable.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstEntregableValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstEntregable);

        jPanel6.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 250, -1));

        btnAgregar.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        btnAgregar.setText("<html> <p align=center>Agrega a</p> <p align=center>la Lista</p> </html>");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel6.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 80, 40));

        btnQuitar.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        btnQuitar.setText("<html> <p align=center>Quitar de</p> <p align=center>la Lista</p> </html>");
        btnQuitar.setEnabled(false);
        btnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarActionPerformed(evt);
            }
        });
        jPanel6.add(btnQuitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 80, 40));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 470, 250));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGuardarRaiz.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        btnGuardarRaiz.setText("<html> <p align=center>Guardar</p> <p align=center>Carpeta Raíz</p> </html>");
        btnGuardarRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarRaizActionPerformed(evt);
            }
        });
        jPanel8.add(btnGuardarRaiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, 40));

        jButton1.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, 40));

        btnAbrirRaiz.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        btnAbrirRaiz.setText("<html> <p align=center>Abrir</p> <p align=center>Carpeta Raíz</p> </html>");
        btnAbrirRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirRaizActionPerformed(evt);
            }
        });
        jPanel8.add(btnAbrirRaiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, 40));

        btnGenerar.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        btnGenerar.setText("<html> <p align=center>Generar</p> <p align=center>Estructura</p> </html>");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });
        jPanel8.add(btnGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 40));

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, 470, 90));

        jTabbedPane1.addTab("Directorio Entregables", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Carpeta raíz"));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel9.add(txtRaizFormato, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 210, -1));

        jLabel4.setText("Carpeta donde se almacenarán los formatos:");
        jPanel9.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        btnRaizFormato.setText("...");
        btnRaizFormato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaizFormatoActionPerformed(evt);
            }
        });
        jPanel9.add(btnRaizFormato, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 40, 20));

        jPanel3.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 310, 100));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Estructura"));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        treFormato.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane3.setViewportView(treFormato);

        jPanel10.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 250, 310));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PckIcoMenu/refresh.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 30, 20));

        jPanel3.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 310, 370));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGuardarRaizFormato.setText("<html> <p align=center>Guardar</p> <p align=center>Carpeta Raíz</p> </html>");
        btnGuardarRaizFormato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarRaizFormatoActionPerformed(evt);
            }
        });
        jPanel11.add(btnGuardarRaizFormato, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 100, 40));

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 100, 40));

        btnAbrirRaizFormato.setText("<html> <p align=center>Abrir</p> <p align=center>Carpeta Raíz</p> </html>");
        btnAbrirRaizFormato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirRaizFormatoActionPerformed(evt);
            }
        });
        jPanel11.add(btnAbrirRaizFormato, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 100, 40));

        jPanel3.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 220, 300));

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Nota: el directorio para formatos será visto");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("por todo el personal docente de la I.E.");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, -1, -1));

        jTabbedPane1.addTab("Directorio Formatos", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 902, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        String idPeriodo;
        ArrayList<ClsEntidadSeccion> arraySeccion;
        ClsSeccion seccion = new ClsSeccion();
        ClsEntregable entregable = new ClsEntregable();
        ClsEntidadEntregable entEntregable = new ClsEntidadEntregable();
        ClsSubEntregable sEntregable = new ClsSubEntregable();
        ClsEntidadSubEntregable sEntEntregable = new ClsEntidadSubEntregable();
        String mesi="";
        String mesf="";
        ClsMatMen mame = new ClsMatMen();   
        ClsMisc m = new ClsMisc();
        boolean success=false;
        String ultimoID = null;
        String month[] = {"ENERO","FEBRERO","MARZO","ABRIL","MAYO","JUNIO","JULIO","AGOSTO","SEPTIEMBRE","OCTUBRE","NOVIEMBRE","DICIEMBRE"};
        //obtengo idperiodo
        idPeriodo = codigoPeriodo.get(cmbPeriodo.getSelectedIndex());
        
        //obtener mes inicio mes fin del periodo                
        try 
        {
            con = ClsConexion.getConection();
            ResultSet rsPer = mame.SeleccionarFechasPeriodo(codigoPeriodo.get(cmbPeriodo.getSelectedIndex()),con);        
                       
            while (rsPer.next())
            {
                //mes de inicio de clases 
                mesi = rsPer.getString("inicio_periodo").substring(3, 5);
                //mes de fin periodo
                mesf = rsPer.getString("fin_periodo").substring(3, 5);
            }
            ClsConexion.closeConnection(con);
        } catch (Exception ex) 
        { Logger.getLogger(FrmEntregables.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //creo carpeta del periodo
        success = (new File(ruta+"/"+cmbPeriodo.getSelectedItem())).mkdirs();
        if(success)
        {
            con = ClsConexion.getConection();
            //entregable.BorrarEntregable(con);
            //obtengo aulas
            arraySeccion = seccion.ListarSeccionPeriodo(idPeriodo);
            //creo carpetas por cada aula
            for(ClsEntidadSeccion i : arraySeccion)
            {
                //carpeta
                success = (new File(ruta+"/"+cmbPeriodo.getSelectedItem()+"/"+i.getNombre_Seccion())).mkdirs();
                if(success)
                {
                    //base de datos
                    entEntregable.setEntregable_nombre(i.getNombre_Seccion());
                    entEntregable.setId_seccion(i.getId_Seccion());
                    entregable.AgregarEntregable(entEntregable, con);                                       
                    try {
                        ultimoID=m.UltimoIdInsertado(con);
                    } catch (Exception ex) {
                        Logger.getLogger(FrmEntregables.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    //crear carpeta de entregable
                    for(String e : Entregable)
                    {
                        try {
                            //base de datos
                            sEntEntregable.setSubentregable_nombre(e);
                            sEntEntregable.setSubentregable_estado("falta");
                            sEntEntregable.setSubentregable_mensaje("");
                            sEntEntregable.setEntregable_id(ultimoID);
                            sEntregable.AgregarEntregable(sEntEntregable, con);
                            
                            success = (new File(ruta+"/"+cmbPeriodo.getSelectedItem()+
                                    "/"+i.getNombre_Seccion()+"/"+e)).mkdirs();
                            if(success)
                            {
                                int meses = obtenerMeses(mesi,mesf);
                                for(int j=0;j<=meses;j++)
                                {
                                    success = (new File(ruta+"/"+cmbPeriodo.getSelectedItem()+
                                            "/"+i.getNombre_Seccion()+"/"+e+"/"+(j+1)+"."+month[(Integer.parseInt(mesi)-1)+j])).mkdirs();                            
                                }
                            }
                        } catch (Exception ex) {
                            Logger.getLogger(FrmEntregables.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }                    
                }
            }
            ClsConexion.closeConnection(con);
            if(success)
            {
                File aux = new File(ruta);
                actualizarArbol(aux.getName(),ruta);
            }            
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Error creando directorio ", "error", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void btnRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaizActionPerformed
        String carpeta="";
        JFileChooser chooser = new JFileChooser();               
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnVal = chooser.showOpenDialog(chooser);
        if(returnVal == JFileChooser.APPROVE_OPTION) 
        {
            carpeta = chooser.getSelectedFile().getName();
            ruta =  chooser.getSelectedFile().getAbsolutePath();   
            txtRaiz.setText(ruta);
            actualizarArbol(carpeta,ruta);
            System.out.println(ruta);
        }
        
        
    }//GEN-LAST:event_btnRaizActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnGuardarRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarRaizActionPerformed
        System.out.println(ruta);
        if(!ruta.equals(""))
        {
            guardarRaiz(ruta);
            JOptionPane.showMessageDialog(this, "Carpeta raíz guardada correctamente: \n"+ruta);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Se debe elegir una carpeta raíz para guardarla.");
        }
        
    }//GEN-LAST:event_btnGuardarRaizActionPerformed

    private void btnAbrirRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirRaizActionPerformed
        if(!ruta.equals(""))
        {
            File dir = new File(ruta);
            if (Desktop.isDesktopSupported()) {
                try {
                    Desktop.getDesktop().open(dir);
                } catch (IOException ex) {
                    Logger.getLogger(FrmEntregables.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        
    }//GEN-LAST:event_btnAbrirRaizActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        FileWriter escribir = null;
        try {
            dlm.addElement(txtEntregable.getText());
            File aux = new File(System.getProperty("user.dir")+"/Data/entregable.txt");
            escribir = new FileWriter(aux);
            BufferedWriter bw = new BufferedWriter(escribir);
            PrintWriter wr = new PrintWriter(bw);
            Iterator it = Entregable.iterator();
            while(it.hasNext()){
                wr.println(it.next());
            }
            wr.append(txtEntregable.getText());
            wr.close();
            bw.close();
            Entregable.add(txtEntregable.getText());
            btnQuitar.setEnabled(false);
            //guardar archivo
        } catch (IOException ex) {
            Logger.getLogger(FrmEntregables.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                escribir.close();
            } catch (IOException ex) {
                Logger.getLogger(FrmEntregables.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed
        Entregable.remove(lstEntregable.getSelectedIndex());
        dlm.remove(lstEntregable.getSelectedIndex());
        FileWriter fichero = null;
        try {

                fichero = new FileWriter(System.getProperty("user.dir")+"/Data/entregable.txt");

                // Escribimos linea a linea en el fichero
                for (String linea : Entregable) {
                        fichero.write(linea + "\n");
                }

                fichero.close();

        } catch (Exception ex) {
                System.out.println("Mensaje de la excepción: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnQuitarActionPerformed

    private void lstEntregableValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstEntregableValueChanged
        btnQuitar.setEnabled(true);
        System.out.println(lstEntregable.getSelectedIndex());
    }//GEN-LAST:event_lstEntregableValueChanged

    private void btnRaizFormatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaizFormatoActionPerformed
        String carpeta="";
        JFileChooser chooser = new JFileChooser();               
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnVal = chooser.showOpenDialog(chooser);
        if(returnVal == JFileChooser.APPROVE_OPTION) 
        {
            carpeta = chooser.getSelectedFile().getName();
            rutaFormato =  chooser.getSelectedFile().getAbsolutePath();   
            txtRaizFormato.setText(rutaFormato);
            actualizarArbolFormato(carpeta,rutaFormato);
            System.out.println(rutaFormato);
        }
    }//GEN-LAST:event_btnRaizFormatoActionPerformed

    private void btnGuardarRaizFormatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarRaizFormatoActionPerformed
        System.out.println(rutaFormato);
        if(!rutaFormato.equals(""))
        {
            guardarRaizFormato(rutaFormato);
            JOptionPane.showMessageDialog(this, "Carpeta raíz para formatos guardada correctamente.");
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Se debe elegir una carpeta raíz para guardarla.");
        }
    }//GEN-LAST:event_btnGuardarRaizFormatoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnAbrirRaizFormatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirRaizFormatoActionPerformed
        if(!rutaFormato.equals(""))
        {
            File dir = new File(rutaFormato);
            if (Desktop.isDesktopSupported()) {
                try {
                    Desktop.getDesktop().open(dir);
                } catch (IOException ex) {
                    Logger.getLogger(FrmEntregables.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btnAbrirRaizFormatoActionPerformed

    private void btnQuitarEstructuraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarEstructuraActionPerformed
        int option = JOptionPane.showConfirmDialog(this, "Se eliminará la estructura de la BD "
                + "incluyendo estados y mensajes."
                + "\n Para eliminar la estructura física dirigase a la carpeta raíz.");
        
        if(option==0)
        {
            String idPeriodo = codigoPeriodo.get(cmbPeriodo.getSelectedIndex());
            ClsEntregable e = new ClsEntregable();
            ClsSubEntregable se = new ClsSubEntregable();
            con = ClsConexion.getConection();
            se.BorrarSubEntregableFiltro(idPeriodo, con);
            e.BorrarEntregableFiltro(idPeriodo, con);
            ClsConexion.closeConnection(con);
        }
        
    }//GEN-LAST:event_btnQuitarEstructuraActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            File aux = new File(ruta);
            actualizarArbol(aux.getName(),ruta);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
            
        File aux = new File(rutaFormato);
        actualizarArbolFormato(aux.getName(),rutaFormato);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void guardarRaiz(String xRuta) {
        ClsRaices raiz = new ClsRaices();    
        con = ClsConexion.getConection();
        raiz.EditarRaizEntregable(xRuta, con);
        ClsConexion.closeConnection(con);
    }
    
    private void guardarRaizFormato(String xRuta) {
        ClsRaices raiz = new ClsRaices();  
        con = ClsConexion.getConection();
        raiz.EditarRaizFormato(xRuta, con);
        ClsConexion.closeConnection(con);
    }
    
    private void cargarComboPeriodo() {
    
        ClsPeriodo periodos = new ClsPeriodo();
        ArrayList<ClsEntidadPeriodo> periodo =  periodos.ListarPeriodo();
        Iterator iterator = periodo.iterator();
        DefaultComboBoxModel DefaultComboBoxModel = new DefaultComboBoxModel();
        DefaultComboBoxModel.removeAllElements();
        cmbPeriodo.removeAllItems();
        String fila[] = new String[4];
     
        while(iterator.hasNext())
        {
        ClsEntidadPeriodo Periodo = new ClsEntidadPeriodo();
        Periodo = (ClsEntidadPeriodo) iterator.next();               
        fila[0] = Periodo.getNombre_Periodo();
        fila[1] = Periodo.getEstado_Periodo();        
            if(Periodo.getEstado_Periodo().equals("Activo"))
            {   
            codigoPeriodo.add(Periodo.getId_Periodo());     
            DefaultComboBoxModel.addElement(Periodo.getNombre_Periodo());        
            }        
        }
        cmbPeriodo.setModel(DefaultComboBoxModel);
        
    }
    
    private String cargarRaiz() {
        con = ClsConexion.getConection();
        ClsRaices raiz = new ClsRaices();
        String texto="";        
        try 
        {
            texto = raiz.SeleccionarRaizEntregable(con);
            
        } catch (Exception ex) {
            Logger.getLogger(FrmEntregables.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            ClsConexion.closeConnection(con);
        }
                  
        return texto;
    }
    
    private String cargarRaizFormato() {
        
        con = ClsConexion.getConection();
        ClsRaices raiz = new ClsRaices();
        String texto = "";
        try {
            texto = raiz.SeleccionarRaizFormato(con);

        } catch (Exception ex) {
            Logger.getLogger(FrmEntregables.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            ClsConexion.closeConnection(con);
        }

        return texto;
    }
    
    
    
    
    
    
    private void actualizarArbol(String xNombre,String xRuta) {
        JTreeFile jtf = new JTreeFile();
        jtf.setJTree(treEstructura);
        jtf.init(xNombre,xRuta);
    }
    
    private void actualizarArbolFormato(String xNombre,String xRuta) {
        JTreeFile jtf = new JTreeFile();
        jtf.setJTree(treFormato);
        jtf.init(xNombre,xRuta);
    }
    
    private void cargaEntregable() {
        BufferedReader reader = null;
        try {
            File aux = new File(System.getProperty("user.dir")+"/Data/entregable.txt");
            reader = new BufferedReader(new FileReader(aux));
            dlm.clear();
            String linea;
            while ( (linea = reader.readLine() ) != null) {                
                dlm.addElement(linea);
                Entregable.add(linea);
            }
            
            lstEntregable.setModel(dlm);
        } catch (IOException ex) {
            System.out.println("Error: " + ex);
        }  finally {
            try {
                reader.close();
            } catch (IOException ex) {
                System.out.println("Error: " + ex);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrirRaiz;
    private javax.swing.JButton btnAbrirRaizFormato;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnGuardarRaiz;
    private javax.swing.JButton btnGuardarRaizFormato;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JButton btnQuitarEstructura;
    private javax.swing.JButton btnRaiz;
    private javax.swing.JButton btnRaizFormato;
    private javax.swing.JComboBox cmbPeriodo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblPeriodo1;
    private javax.swing.JList<String> lstEntregable;
    private javax.swing.JTree treEstructura;
    private javax.swing.JTree treFormato;
    private javax.swing.JTextField txtEntregable;
    private javax.swing.JTextField txtRaiz;
    private javax.swing.JTextField txtRaizFormato;
    // End of variables declaration//GEN-END:variables
}
