/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package PckInterfaces;

import PckConexion.ClsConexion;
import PckEntidad.ClsEntidadEgresos;
import PckEntidad.ClsEntidadPersonal;
import PckNegocio.ClsEgresos;
import PckNegocio.ClsIngresosEgresos;
import PckNegocio.ClsPersonal;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import prymatricula.ClsMisc.miRender;

/**
 *
 * @author kmv
 */
public class FrmEgresos extends javax.swing.JInternalFrame  {   
   
    
    SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
    Date date = new Date();
    private String strCodigo;
    public FrmIngresosEgresos objFrame1;
    ArrayList<String> codigoPersonal = new ArrayList();
    Connection con = null;
    /**
     * Creates new form FrmEgresos
     */
    public FrmEgresos() {
        initComponents();
        
        jdcFechaEgreso.setDate(date);
        comboPersona();
        tablaEgreso();
        activaBotones(true,false,false,false);
        desactivaCampos();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEgresos = new javax.swing.JTable();
        jdcFechaEgreso = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbPersona = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtConcepto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFecha = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();

        setTitle("Egresos");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PckIconos/ic_library_add_black_24dp.png"))); // NOI18N
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel2.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 40, 40));

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PckIconos/ic_save_black_24dp.png"))); // NOI18N
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel2.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 40, 40));

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PckIconos/ic_mode_edit_black_24dp.png"))); // NOI18N
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel2.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 40, 40));

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PckIconos/ic_delete_forever_black_24dp.png"))); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 40, 40));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PckIconos/ic_exit_to_app_black_24dp.png"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 40, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 120, 80, 290));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Egresos"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblEgresos.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        tblEgresos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEgresos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEgresosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEgresos);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 700, 260));

        jdcFechaEgreso.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jdcFechaEgreso.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jdcFechaEgresoPropertyChange(evt);
            }
        });
        jPanel3.add(jdcFechaEgreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 120, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 750, 340));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jLabel1.setText("Usuario:");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 80, 20));

        cmbPersona.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        cmbPersona.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPersona.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPersonaItemStateChanged(evt);
            }
        });
        jPanel4.add(cmbPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 280, -1));

        jLabel2.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jLabel2.setText("Concepto:");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        txtConcepto.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jPanel4.add(txtConcepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 280, -1));

        jLabel4.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jLabel4.setText("Monto:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 60, 20));

        txtMonto.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        txtMonto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMontoKeyTyped(evt);
            }
        });
        jPanel4.add(txtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 280, -1));

        jLabel5.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jLabel5.setText("Fecha:");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 20));

        txtFecha.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jPanel4.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 140, -1));

        jLabel3.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jLabel3.setText("Descripción:");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 70, -1));

        jScrollPane2.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N

        txtDescripcion.setColumns(20);
        txtDescripcion.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        txtDescripcion.setLineWrap(true);
        txtDescripcion.setRows(5);
        txtDescripcion.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtDescripcion);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 310, 110));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 750, 190));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 952, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
  
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed
    public void fijar(FrmIngresosEgresos obj) {
            this.objFrame1 = obj;
    }
    private void cmbPersonaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPersonaItemStateChanged
       if(cmbPersona.getHeight()>0)
       {       
        System.out.println(codigoPersonal.get(cmbPersona.getSelectedIndex()));
       }
    }//GEN-LAST:event_cmbPersonaItemStateChanged

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        activaCampos();
        cmbPersona.requestFocus();
        txtFecha.setDate(date);
        activaBotones(true,true,false,false);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        ClsEgresos e = new ClsEgresos();
        ClsEntidadEgresos ee = new ClsEntidadEgresos();
        ee.setId_Persona(codigoPersonal.get(cmbPersona.getSelectedIndex()));
        ee.setConcepto_Egreso(txtConcepto.getText());
        ee.setDescripcion_Egreso(txtDescripcion.getText());
        ee.setMonto_Egreso(txtMonto.getText()); 
        ee.setFecha_Egreso(formato.format(txtFecha.getDate())); 
        con = ClsConexion.getConection();
        e.AgregarEgreso(ee,con); 
        ClsConexion.closeConnection(con);
        tablaEgreso();
        activaBotones(true,false,false,false);
        btnNuevo.requestFocus();
        try
        {
            objFrame1.tablaEgresos();
            objFrame1.calculaCierre();
        }catch(Exception ex)
        {
            Logger.getLogger(FrmEgresos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
      
        ClsEgresos e = new ClsEgresos();
        ClsEntidadEgresos ee = new ClsEntidadEgresos();
        
        ee.setId_Persona(codigoPersonal.get(cmbPersona.getSelectedIndex()));
        ee.setConcepto_Egreso(txtConcepto.getText());
        ee.setDescripcion_Egreso(txtDescripcion.getText());
        ee.setMonto_Egreso(txtMonto.getText()); 
        ee.setFecha_Egreso(formato.format(txtFecha.getDate())); 
        con = ClsConexion.getConection();
        e.ModificaEgreso(ee, strCodigo,con); 
        ClsConexion.closeConnection(con);
        tablaEgreso();
        activaBotones(true,false,false,false);
        btnNuevo.requestFocus();
        limpiaCampos();
        desactivaCampos();
        try
        {
            objFrame1.tablaEgresos();
            objFrame1.calculaCierre();
        }
        catch(Exception ex)
        {
            Logger.getLogger(FrmEgresos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void tblEgresosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEgresosMouseClicked
        int reg;
      DefaultTableModel dtm;
      reg = tblEgresos.getSelectedRow();
        if(reg == -1)
        { JOptionPane.showMessageDialog(null, "Debe Seleccionar un registro"); 
        }
        else
        {
            try {
                dtm = (DefaultTableModel)tblEgresos.getModel();
                strCodigo = ((String)dtm.getValueAt(reg, 0));
                cmbPersona.setSelectedItem(((String)dtm.getValueAt(reg, 1)));
                txtConcepto.setText((String)dtm.getValueAt(reg, 2));                
                txtDescripcion.setText((String)dtm.getValueAt(reg, 3));
                txtMonto.setText((String)dtm.getValueAt(reg, 4));
                txtFecha.setDate(jdcFechaEgreso.getDate());
            } catch (Exception ex) {
                Logger.getLogger(FrmPeriodo.class.getName()).log(Level.SEVERE, null, ex);
            }            
            activaBotones(true,false,true,true);  
            activaCampos(); 
            
            //valida que no tenga permitido editar egreso
            if(!FrmPrincipal.editarEgreso){
                
                if(jdcFechaEgreso.getDate().before(date)) {
                    btnModificar.setEnabled(false);
                }
            }
            
        }
    }//GEN-LAST:event_tblEgresosMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        ClsEgresos e = new ClsEgresos();
        con = ClsConexion.getConection();
        e.EliminarEgreso(strCodigo,con);
        ClsConexion.closeConnection(con);
        tablaEgreso();
        activaBotones(true,false,false,false);
        btnNuevo.requestFocus();
        limpiaCampos();
        desactivaCampos();
        try
        {
            objFrame1.tablaEgresos();
            objFrame1.calculaCierre();
        }
        catch(Exception ex)
        {
            Logger.getLogger(FrmEgresos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtMontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontoKeyTyped
       char c = evt.getKeyChar();
        if ( !(Character.isDigit(c) ||
        (c == KeyEvent.VK_BACK_SPACE) ||
        (c == KeyEvent.VK_DELETE) ||
        (c == KeyEvent.VK_SPACE) || 
        (c == KeyEvent.VK_PERIOD) ))
        {            
        evt.consume();
        }
    }//GEN-LAST:event_txtMontoKeyTyped

    private void jdcFechaEgresoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jdcFechaEgresoPropertyChange
        
        if (jdcFechaEgreso.getDate()!= null) {
            
            tablaEgreso();
            
            if(!FrmPrincipal.editarEgreso){
                
                if(jdcFechaEgreso.getDate().before(date)) {
                    btnModificar.setEnabled(false);
                }
            }
        }
    }//GEN-LAST:event_jdcFechaEgresoPropertyChange
   
    private void limpiaCampos()
    {    
        txtConcepto.setText("");
        txtDescripcion.setText("");
        txtMonto.setText("");
        txtFecha.setDate(null);
    }
    
    private void activaCampos()
    {
        cmbPersona.setEnabled(true);
        txtConcepto.setEnabled(true);
        txtDescripcion.setEnabled(true);
        txtMonto.setEnabled(true);
        txtFecha.setEnabled(true);
    }
    private void desactivaCampos()
    {
        cmbPersona.setEnabled(false);
        txtConcepto.setEnabled(false);
        txtDescripcion.setEnabled(false);
        txtMonto.setEnabled(false);
        txtFecha.setEnabled(false);
    }
    private void activaBotones(boolean n,boolean g, boolean m, boolean e)
    {
        btnNuevo.setEnabled(n);
        btnAgregar.setEnabled(g);
        btnModificar.setEnabled(m);
        btnEliminar.setEnabled(e);
    }
    private void comboPersona()
    {
        codigoPersonal.clear();
        ClsPersonal personas = new ClsPersonal();
        con = ClsConexion.getConection();
        ArrayList<ClsEntidadPersonal> persona =  personas.SeleccionarPersonalNombre(con);
        Iterator it = persona.iterator();
        DefaultComboBoxModel dcm = new DefaultComboBoxModel();
        dcm.removeAllElements();
        cmbPersona.removeAllItems();
        String fila[] = new String[3];
            
        while(it.hasNext())
        {
            ClsEntidadPersonal Persona = (ClsEntidadPersonal) it.next();
            
            if(Persona.getPersonal_estado().equals("A")) {
                codigoPersonal.add(Persona.getPersonal_id());
                fila[0] = Persona.getPersonal_nombre();
                dcm.addElement(fila[0]);      
            } 
                     
        }
        ClsConexion.closeConnection(con);
        cmbPersona.setModel(dcm);           
    }
    
    
    private void tablaEgreso()
    {
        String titulos[] = {"ID","PERSONA","CONCEPTO","DESCRIPCION","MONTO"};
        ClsIngresosEgresos egresos = new ClsIngresosEgresos();
        con = ClsConexion.getConection();
        String fecha = formato.format(jdcFechaEgreso.getDate());
        ArrayList<ClsEntidadEgresos> egreso = egresos.SeleccionarEgresos(fecha, con);
        Iterator iterator = egreso.iterator();
        DefaultTableModel dtm =new DefaultTableModel(null,titulos){
        public boolean isCellEditable(int rowIndex,int columnIndex){return false;} 
        };         
        String fila[] = new String[6];
        while(iterator.hasNext())
        {
            ClsEntidadEgresos Egreso = new ClsEntidadEgresos();
            Egreso = (ClsEntidadEgresos) iterator.next();
            fila[0] = Egreso.getId_Egreso();
            fila[1] = Egreso.getNombre_Persona();
            fila[2] = Egreso.getConcepto_Egreso();
            fila[3] = Egreso.getDescripcion_Egreso();
            fila[4] = Egreso.getMonto_Egreso();            
            dtm.addRow(fila);
        }
        ClsConexion.closeConnection(con);
        tblEgresos.setModel(dtm);        
        tblEgresos.removeColumn(tblEgresos.getColumnModel().getColumn(0));
        TableColumn  columnaNombre =tblEgresos.getColumnModel().getColumn(0);
                columnaNombre.setPreferredWidth(160);
        TableColumn  columnaApe =tblEgresos.getColumnModel().getColumn(1);
        columnaApe.setPreferredWidth(160);
        TableCellRenderer tcr =  tblEgresos.getTableHeader().getDefaultRenderer();  
        miRender mr = new miRender(tcr);       
        mr.getTableCellRendererComponent(tblEgresos, fila, isSelected, isIcon, WIDTH, WIDTH);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox cmbPersona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser jdcFechaEgreso;
    private javax.swing.JTable tblEgresos;
    private javax.swing.JTextField txtConcepto;
    private javax.swing.JTextArea txtDescripcion;
    private com.toedter.calendar.JDateChooser txtFecha;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
}
