/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PckInterfaces;

import PckConexion.ClsConexion;
import PckEntidad.ClsEntidadPeriodo;
import PckEntidad.ClsEntidadSeccion;
import PckEntidad.ClsEntidadSubEntregable;
import PckNegocio.ClsMatMen;
import PckNegocio.ClsPeriodo;
import PckNegocio.ClsRaices;
import PckNegocio.ClsSeccion;
import PckNegocio.ClsSubEntregable;
import java.awt.Desktop;
import static java.awt.image.ImageObserver.WIDTH;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import prymatricula.ClsMisc;
import static prymatricula.ClsMisc.obtenerMeses;

/**
 *
 * @author Kevin
 */
public class FrmEntregablesEstado extends javax.swing.JInternalFrame {
    ArrayList<String> codigoPeriodo = new ArrayList();
    ArrayList<String> codigoSeccion = new ArrayList();
    ArrayList<String> numeroMes = new ArrayList();
    private String idEntregable;
    /*
    *con: Variable de conexion con ClsConexion
    */
    Connection con;
    
    DefaultComboBoxModel dcmMeses = new DefaultComboBoxModel();
        
    /*
    *month[]: Array de meses 
    *Valores: Desde Enero hasta Diciembre
    */
    String month[] = {"ENERO","FEBRERO","MARZO","ABRIL",
        "MAYO","JUNIO","JULIO","AGOSTO","SEPTIEMBRE","OCTUBRE","NOVIEMBRE","DICIEMBRE"};

    
    public FrmEntregablesEstado() {
        initComponents();
        
        /*
        *modelo para Estado: agrega los estados para cmbEstado
        */
        DefaultComboBoxModel dcm = new DefaultComboBoxModel();        
        dcm.addElement("APROBADO");
        dcm.addElement("CORREGIR");
        dcm.addElement("PENDIENTE");
        dcm.addElement("FALTA");
        cmbEstado.setModel(dcm);
        
        cargaPeriodo();
        cargaSeccion();
        cargaMes();
        actualizarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cmbPeriodo = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        cmbSeccion = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEstado = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        cmbEstado = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtComentario = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        btnEstado = new javax.swing.JButton();
        btnAbrir = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        cmbMes = new javax.swing.JComboBox<>();

        setTitle("Estado Entregables");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccione un Aula"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jLabel8.setText("Periodo:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 120, 20));

        cmbPeriodo.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        cmbPeriodo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPeriodo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPeriodoItemStateChanged(evt);
            }
        });
        jPanel2.add(cmbPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 190, -1));

        jLabel9.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jLabel9.setText("Aula:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 20));

        cmbSeccion.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        cmbSeccion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbSeccionItemStateChanged(evt);
            }
        });
        jPanel2.add(cmbSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 190, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 260, 150));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Estado Entregables"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblEstado.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        tblEstado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEstado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEstadoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblEstado);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 690, 170));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 750, 240));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Estado"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbEstado.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel4.add(cmbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 190, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 260, 70));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Comentario"));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtComentario.setColumns(20);
        txtComentario.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        txtComentario.setLineWrap(true);
        txtComentario.setRows(5);
        jScrollPane1.setViewportView(txtComentario);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 190, 210));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 230, 260));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEstado.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        btnEstado.setText("Editar Estado");
        btnEstado.setEnabled(false);
        btnEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadoActionPerformed(evt);
            }
        });
        jPanel6.add(btnEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 110, -1));

        btnAbrir.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        btnAbrir.setText("Abrir Carpeta");
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });
        jPanel6.add(btnAbrir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 110, -1));

        btnSalir.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel6.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 110, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 190, 170));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Vista por Mes"));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbMes.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        cmbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbMes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbMesItemStateChanged(evt);
            }
        });
        jPanel7.add(cmbMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 150, -1));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 190, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbPeriodoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPeriodoItemStateChanged
        if(cmbPeriodo.getSelectedIndex() != -1)
        {
            cargaSeccion();
            cargaMes();
        }
    }//GEN-LAST:event_cmbPeriodoItemStateChanged

    private void cmbSeccionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbSeccionItemStateChanged
        if(cmbSeccion.getSelectedIndex() != -1)
        {
            actualizarTabla();
        }
    }//GEN-LAST:event_cmbSeccionItemStateChanged

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void cmbMesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbMesItemStateChanged
        
        if(cmbMes.getSelectedIndex() != -1){
            actualizarTabla();
        }
       
    }//GEN-LAST:event_cmbMesItemStateChanged

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
        try 
        {
            ClsRaices ra = new ClsRaices();
            String url = ra.SeleccionarRaizEntregable(con);
            
            if(!url.equals(""))
            {
            File dir = new File(url);
                if (Desktop.isDesktopSupported()) 
                {
                    try
                    {
                        Desktop.getDesktop().open(dir);
                    } catch (IOException ex) {
                        Logger.getLogger(FrmEntregables.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }           
            
        } catch (Exception ex) {
            Logger.getLogger(FrmEntregablesEstado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAbrirActionPerformed

    private void tblEstadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEstadoMouseClicked
        int reg;
        DefaultTableModel dtm = new DefaultTableModel();
        reg = tblEstado.getSelectedRow();
        if(reg == -1)
        {
            JOptionPane.showMessageDialog(null, "Debe Seleccionar un registro");
        }
        else
        {
            dtm = (DefaultTableModel)tblEstado.getModel();
            idEntregable = (String) dtm.getValueAt(reg, 0);
            cmbEstado.setSelectedItem((String) dtm.getValueAt(reg, 4)); 
            txtComentario.setText((String) dtm.getValueAt(reg, 5));
            btnEstado.setEnabled(true);
        }
    }//GEN-LAST:event_tblEstadoMouseClicked

    private void btnEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadoActionPerformed
        
        ClsSubEntregable se = new ClsSubEntregable();
        con = ClsConexion.getConection();
        se.EditarSubEntregableEstadoComentario(idEntregable, cmbEstado.getSelectedItem().toString(),
                    txtComentario.getText(),con);
        ClsConexion.closeConnection(con);
        btnEstado.setEnabled(false);        
        actualizarTabla();
        
    }//GEN-LAST:event_btnEstadoActionPerformed
    
    private void actualizarTabla() {
        try 
        {
            ClsRaices ra = new ClsRaices();
            String url;
            String mes;
            String periodo;
            String aula;
            String titulos[] = {"ID","Entregable","Archivos","Ultimo Subido","Estado","Comentario"};
            ClsSubEntregable se = new ClsSubEntregable();
            con = ClsConexion.getConection();
            url = ra.SeleccionarRaizEntregable(con);
            periodo = cmbPeriodo.getSelectedItem().toString();
            aula = cmbSeccion.getSelectedItem().toString();
            mes = cmbMes.getSelectedItem().toString();
            ArrayList<ClsEntidadSubEntregable> ese = 
                    se.SeleccionarSubEntregables(codigoSeccion.get(cmbSeccion.getSelectedIndex()), con);
            String fila[]= new String[7];
            DefaultTableModel dtm = new DefaultTableModel(null,titulos){
                @Override
                public boolean isCellEditable(int rowIndex,int columnIndex){return false;}
            };
            for(ClsEntidadSubEntregable e : ese)
            {                   
                fila[0] = e.getSubentregable_id();
                fila[1] = e.getSubentregable_nombre();  
                File folder = new File(url+"/"+periodo+"/"+aula+"/"+fila[1]+"/"
                        +numeroMes.get(cmbMes.getSelectedIndex())+"."+mes);
                int a = listFilesForFolder(folder);
                fila[2] = String.valueOf(a);
                fila[3] = e.getSubentregable_fecha();
                fila[4] = e.getSubentregable_estado();
                fila[5] = e.getSubentregable_mensaje();
                dtm.addRow(fila);
            }            
            tblEstado.setModel(dtm);
            tblEstado.removeColumn(tblEstado.getColumnModel().getColumn(0)); 
            //CENRAR COLUMNAS Y FILAS (ClsMisc)
            TableCellRenderer tcr =  tblEstado.getTableHeader().getDefaultRenderer();                       
            ClsMisc.miRender mr = new ClsMisc.miRender(tcr);
            mr.getTableCellRendererComponent(tblEstado, fila, isSelected, isIcon, WIDTH, 1);
            mr.getTableCellRendererComponent(tblEstado, fila, isSelected, isIcon, WIDTH, 2);
            mr.getTableCellRendererComponent(tblEstado, fila, isSelected, isIcon, WIDTH, 3);
        } catch (Exception ex) {
            Logger.getLogger(FrmEntregablesEstado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private int listFilesForFolder(final File folder) {
        int cont = 0;
        for (final File fileEntry : folder.listFiles()) 
        {
            if (fileEntry.isDirectory()) {
                listFilesForFolder(fileEntry);
            } else {
                System.out.println(fileEntry.getName());
                cont++;
            }
        }
        return cont;
    }
    
    private void cargaMes() {
        String mesi="";
        String mesf="";
        ClsMatMen mame = new ClsMatMen();   
        dcmMeses.removeAllElements();
        //obtener mes inicio mes fin del periodo                
        try 
        {
            con = ClsConexion.getConection();
            ResultSet rsPer = mame.SeleccionarFechasPeriodo(codigoPeriodo.get(cmbPeriodo.getSelectedIndex()),con);        
                       
            while (rsPer.next())
            {
                //mes de inicio de clases 
                mesi = rsPer.getString("inicio_periodo").substring(3, 5);
                //mes de fin periodo
                mesf = rsPer.getString("fin_periodo").substring(3, 5);
            }
            ClsConexion.closeConnection(con);
        } catch (Exception ex) 
        { Logger.getLogger(FrmEntregables.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        int meses = obtenerMeses(mesi,mesf);        
        for(int j=0;j<=meses;j++)
        { 
            dcmMeses.addElement(month[(Integer.parseInt(mesi)-1)+j]);    
            numeroMes.add(String.valueOf(j+1));
        }  
        cmbMes.setModel(dcmMeses);
    }
    private void cargaPeriodo() {
        ClsPeriodo periodos = new ClsPeriodo();
        ArrayList<ClsEntidadPeriodo> periodo =  periodos.ListarPeriodo();
        Iterator iterator = periodo.iterator();
        DefaultComboBoxModel DefaultComboBoxModel = new DefaultComboBoxModel();
        DefaultComboBoxModel.removeAllElements();
        cmbPeriodo.removeAllItems();
        String fila[] = new String[4];     
        while(iterator.hasNext())
        {
        ClsEntidadPeriodo Periodo = new ClsEntidadPeriodo();
        Periodo = (ClsEntidadPeriodo) iterator.next();               
        fila[0] = Periodo.getNombre_Periodo();
        fila[1] = Periodo.getEstado_Periodo();        
            if(Periodo.getEstado_Periodo().equals("Activo"))
            {   
            codigoPeriodo.add(Periodo.getId_Periodo());     
            DefaultComboBoxModel.addElement(Periodo.getNombre_Periodo());        
            }        
        }
        cmbPeriodo.setModel(DefaultComboBoxModel);
        //cambia estado del combo a lleno
        //conComboPeriodo2=1;
    }
    
    private void cargaSeccion() {
        codigoSeccion.clear();
        ClsSeccion secciones = new ClsSeccion();
        ArrayList<ClsEntidadSeccion> seccion =  secciones.ListarSeccion();
        Iterator it = seccion.iterator();
        DefaultComboBoxModel dcm = new DefaultComboBoxModel();
        dcm.removeAllElements();
        cmbSeccion.removeAllItems();
        String fila2[] = new String[5];        
        while(it.hasNext())
        {
        ClsEntidadSeccion Seccion = (ClsEntidadSeccion) it.next();             
        fila2[0] = Seccion.getNombre_Seccion();
        fila2[1] = Seccion.getEstado_Periodo();       
        fila2[3] = Seccion.getNombre_Periodo();
        
            if (codigoPeriodo.get(cmbPeriodo.getSelectedIndex()).equals(Seccion.getId_Periodo())) 
            {
                codigoSeccion.add(Seccion.getId_Seccion());
                dcm.addElement(fila2[0]);
            }
        }
        cmbSeccion.setModel(dcm); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnEstado;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbMes;
    private javax.swing.JComboBox cmbPeriodo;
    private javax.swing.JComboBox cmbSeccion;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblEstado;
    private javax.swing.JTextArea txtComentario;
    // End of variables declaration//GEN-END:variables
}
