/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package PckInterfaces;

import PckConexion.ClsConexion;
import PckEntidad.ClsEntidadEgresoReporte;
import PckEntidad.ClsEntidadEgresos;
import PckEntidad.ClsEntidadIngEgre;
import static PckInterfaces.FrmPrincipal.dskpPrincipal;
import PckNegocio.ClsIngresosEgresos;
import java.awt.Component;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author kmv
 */
public class FrmIngresosEgresos extends javax.swing.JInternalFrame {
SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
Date date = new Date();
double ingre=0.0,egre=0.0;
double cierre=0.0;
String  url2 ="/Reportes/RptIngresos.jasper";
String  url3 ="/Reportes/RptIngresos.jrxml";
String  url4 ="/Reportes/RptEgresos.jasper";
String  url5 ="/Reportes/RptEgresos.jrxml";
String  url6 ="/Reportes/RptCierreCaja.jasper";
String  url7 ="/Reportes/RptCierreCaja.jrxml";
String  url ="/Reportes/RptEgresoss.jrxml";
Connection con;
    public FrmIngresosEgresos() {
        initComponents();
        jdcFecha.setDate(date);
        
        if(!FrmPrincipal.editarEgreso){
            btnEditar.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblIngresos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtIngresos = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jdcFecha = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEgresos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtEgresos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCierre = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();

        setTitle("Ingresos y Egresos");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingresos del Día"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblIngresos.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        tblIngresos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblIngresos);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 620, 190));

        jLabel1.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jLabel1.setText("Total Ingresos:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 80, -1));

        txtIngresos.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jPanel2.add(txtIngresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 80, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 660, 250));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha a Evaluar"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jdcFecha.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jdcFecha.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jdcFechaPropertyChange(evt);
            }
        });
        jPanel3.add(jdcFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 120, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 160, 60));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Egresos"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblEgresos.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        tblEgresos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblEgresos);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 620, 190));

        jLabel2.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jLabel2.setText("Total Egresos:");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 80, 20));

        txtEgresos.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jPanel4.add(txtEgresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 80, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 660, 250));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setText("Total Cierre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 616, -1, 30));
        jPanel1.add(txtCierre, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 620, 80, 20));

        btnEditar.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PckIconos/edit.png"))); // NOI18N
        btnEditar.setText("<html> <p align=center>Editar</p> <p align=center>Egresos</p> </html>");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 290, 120, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PckImages/ingreegre.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 290, 50));

        jButton1.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PckIconos/remote_desktop_laptop.png"))); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 390, 120, 40));

        btnReporte.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        btnReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PckIconos/full_page.png"))); // NOI18N
        btnReporte.setText("<html> <p align=center>Generar</p> <p align=center>Reporte</p> </html>");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });
        jPanel1.add(btnReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 340, 120, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 864, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jdcFechaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jdcFechaPropertyChange
        if (jdcFecha.getDate()!= null)
        {
            tablaIngresos();
            tablaEgresos();
            calculaCierre();
        }
        
    }//GEN-LAST:event_jdcFechaPropertyChange

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

        FrmEgresos per = new FrmEgresos();     
        int x = (dskpPrincipal.getWidth() / 2) - per.getWidth() / 2;
        int y = (dskpPrincipal.getHeight() / 2) - per.getHeight() / 2; 
        if (per.isShowing()) 
        {
            per.setLocation(x, y);
        } 
        else 
        {
            dskpPrincipal.add(per);            
            per.fijar(this);
            per.setLocation(x, y);
            per.show();
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        //REPORTE DE DOS TABLAS//
        //variables generales
        double auxi=0.0;
        double auxe=0.0;
        double total=0.0;
        String fecha = formato.format(jdcFecha.getDate());
        ClsIngresosEgresos cie = new ClsIngresosEgresos();
       
        //REPORTE FINALLLLL  
        //Los dataSource se pueden enviar como parametros, declarandolos como tipo LIST,
        //luego obtener los sbreportes indicando de donde obtendran sus debidos datasource
        //asi:  new net.sf.jasperreports.engine.data.JRBeanCollectionDataSource($P{SUB_DATA_SOURCE})
      
        //1 Obtenemos los dataSource que utilizaremos en los reportes
        ArrayList<ClsEntidadIngEgre> dataBean = new ArrayList<ClsEntidadIngEgre>();        
        con = ClsConexion.getConection();
        dataBean = cie.SeleccionarIngresos(fecha,con);    
        for(ClsEntidadIngEgre i: dataBean)
        { 
            if(!i.Tipo.equals("anulada")) 
            {
                auxi = auxi + Double.parseDouble(i.Monto);
            }                
        } 
        ClsConexion.closeConnection(con);
        con = ClsConexion.getConection();
        ArrayList<ClsEntidadEgresoReporte> dataBean2 = new ArrayList<ClsEntidadEgresoReporte>();        
        dataBean2 = cie.SeleccionarEgresoReporte(fecha,con);
        for(ClsEntidadEgresoReporte i: dataBean2)
        { 
          auxe = auxe + Double.parseDouble(i.monto);
        }
        
        total = auxi-auxe;
        ClsConexion.closeConnection(con);
        //2 COMPILAMOS LOS SUBREPORTS CON EL REPORTE PRINCIPAL
        try {            
            
            //principal
            JasperDesign jasperDesign = JRXmlLoader.load(System.getProperty("user.dir")+url7);
            JasperReport ReportMain = JasperCompileManager.compileReport(jasperDesign);
            System.out.print(System.getProperty("user.dir"));

            Map<String, Object> params = new HashMap();
            params.put("auxi",String.valueOf(auxi));
            params.put("auxe",String.valueOf(auxe));
            params.put("total",String.valueOf(total));
            params.put("dsreport1", dataBean);
            params.put("dsreport2", dataBean2);
            params.put("fecha", fecha);
            params.put("SUBREPORT_DIR", System.getProperty("user.dir")+"\\Reportes\\");
            JRBeanCollectionDataSource ds2 = new JRBeanCollectionDataSource(null);
            JasperPrint print = JasperFillManager.fillReport(ReportMain, params, ds2);     
            
            JasperViewer view = new JasperViewer(print,false);
            view.setTitle("Cierre de Caja");
            view.setVisible(true);            
            
        } catch (JRException ex) {
            Logger.getLogger(FrmIngresosEgresos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_btnReporteActionPerformed
    

    private void tablaIngresos()
    {        
        String fecha = formato.format(jdcFecha.getDate());
        ingre=0.0;
        String titulos[] = {"Alumno","Concepto","Seccion","Num. Boleta","Monto","ID Boleta"};
        ClsIngresosEgresos cie = new ClsIngresosEgresos();
        con = ClsConexion.getConection();
        ArrayList<ClsEntidadIngEgre> ingreso = cie.SeleccionarIngresos(fecha,con);        
        Iterator iterator = ingreso.iterator();
        DefaultTableModel dtm =new DefaultTableModel(null,titulos){
        public boolean isCellEditable(int rowIndex,int columnIndex){return false;} 
        };                 
        String fila[] = new String[12];                
        while(iterator.hasNext())
        {
            ClsEntidadIngEgre Ingreso = new ClsEntidadIngEgre();
            Ingreso = (ClsEntidadIngEgre) iterator.next();
            fila[0] = Ingreso.getNiño();
            fila[1] = Ingreso.getConcepto();
            fila[2] = Ingreso.getSeccion();
            fila[3] = Ingreso.getRecibo();
            fila[4] = Ingreso.getMonto();
            fila[5] = Ingreso.getId_Boleta();
            fila[6] = Ingreso.getTipo();                             

            if(!fila[6].equals("anulada") && Ingreso.getTipo_pago().equals("caja")) 
            {
                ingre = ingre + Double.parseDouble(fila[4]);
            }
            dtm.addRow(fila);                  
        }
        ClsConexion.closeConnection(con);
            tblIngresos.setModel(dtm);
            TableColumn columnaObs =tblIngresos.getColumnModel().getColumn(0);
            columnaObs.setPreferredWidth(210);
            TableColumn columnaConcepto =tblIngresos.getColumnModel().getColumn(1);
            columnaConcepto.setPreferredWidth(190);    
            TableColumn asd =tblIngresos.getColumnModel().getColumn(2);            
            asd.setPreferredWidth(100);    
            tblIngresos.removeColumn(tblIngresos.getColumnModel().getColumn(5));

        TableCellRenderer tcr =  tblIngresos.getTableHeader().getDefaultRenderer();  
        //CENTRAR CABECERAS DE LA TABLA
        miRender mr = new miRender(tcr);       
        mr.getTableCellRendererComponent(tblIngresos, fila, isSelected, isIcon, WIDTH, WIDTH);

        txtIngresos.setText(String.valueOf(ingre));
    }
    
    public void calculaCierre()
    {
        cierre = ingre - egre;
        txtCierre.setText(String.valueOf(cierre));
    }
    
    public void tablaEgresos(){
            egre=0.0;
            String fecha = formato.format(jdcFecha.getDate());
            
            String titulos[] = {"ID","Persona","Concepto","Descripción","Monto"};
            ClsIngresosEgresos egresos = new ClsIngresosEgresos();
            con = ClsConexion.getConection();
            ArrayList<ClsEntidadEgresos> egreso = egresos.SeleccionarEgresos(fecha,con);
            Iterator iterator = egreso.iterator();
            DefaultTableModel dtm =new DefaultTableModel(null,titulos){
        public boolean isCellEditable(int rowIndex,int columnIndex){return false;} 
        };          
            String fila[] = new String[7];            
            while(iterator.hasNext()){
                ClsEntidadEgresos Egreso = new ClsEntidadEgresos();
                Egreso = (ClsEntidadEgresos) iterator.next();
                fila[0] = Egreso.getId_Egreso();
                fila[1] = Egreso.getNombre_Persona();
                fila[2] = Egreso.getConcepto_Egreso();
                fila[3] = Egreso.getDescripcion_Egreso();
                fila[4] = Egreso.getMonto_Egreso();
//                fila[5] = Egreso.getFecha_Egreso();
                dtm.addRow(fila);     
                
                egre = egre + Double.parseDouble(fila[4]);
            }
            ClsConexion.closeConnection(con);
            tblEgresos.setModel(dtm);
            tblEgresos.removeColumn(tblEgresos.getColumnModel().getColumn(0));
            TableColumn columnaObs =tblEgresos.getColumnModel().getColumn(0);
                columnaObs.setPreferredWidth(160);
            TableColumn columnaConcepto =tblEgresos.getColumnModel().getColumn(1);
                columnaConcepto.setPreferredWidth(160);    
//               tblEgresos.removeColumn(tblEgresos.getColumnModel().getColumn(5));
           
            TableCellRenderer tcr =  tblEgresos.getTableHeader().getDefaultRenderer();  
            //CENTRAR CABECERAS DE LA TABLA
            miRender mr = new miRender(tcr);       
            mr.getTableCellRendererComponent(tblEgresos, fila, isSelected, isIcon, WIDTH, WIDTH);
            
            txtEgresos.setText(String.valueOf(egre)); 
            
            
    }
    
    class miRender implements javax.swing.table.TableCellRenderer{
    TableCellRenderer tcr;
    public miRender(TableCellRenderer tcr){
        this.tcr = tcr;
    }

    public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
        javax.swing.JComponent wth = (javax.swing.JComponent) tcr.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
        javax.swing.JLabel label = (javax.swing.JLabel)wth;
        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        return wth;
    }
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnReporte;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser jdcFecha;
    private javax.swing.JTable tblEgresos;
    private javax.swing.JTable tblIngresos;
    private javax.swing.JTextField txtCierre;
    private javax.swing.JTextField txtEgresos;
    private javax.swing.JTextField txtIngresos;
    // End of variables declaration//GEN-END:variables
}


