/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package PckInterfaces;

import PckConexion.ClsConexion;
import PckNegocio.ClsAcceso;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import org.apache.commons.codec.digest.DigestUtils;
import prymatricula.Panel;

/**
 *
 * @author John Kevin Montes De Oca Vizcarra
 */
public class FrmMpsLogin extends javax.swing.JFrame {

    Connection con=null;
    /** Creates new form FrmMpsLogin */
    public FrmMpsLogin() {
        initComponents();
//        try {
//            
//            
//            String url1="/Img/sunshine.png";
//            String urlSistema1 = System.getProperty("user.dir");
//            //urlSistema = urlSistema.replace("\\", "/");
//            //System.out.println(urlSistema+url);
//            Image fot1 = null;
//            try {
//                fot1 = ImageIO.read(new File(urlSistema1+url1));
//                setIconImage(fot1);
//            } catch (IOException ex) {
//                Logger.getLogger(FrmMpsLogin.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        } catch (Exception ex) {
//            
//        }
        this.getRootPane().setWindowDecorationStyle(JRootPane.NONE);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        btnAcceso = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.setPreferredSize(new java.awt.Dimension(687, 320));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Droid Sans", 0, 12)); // NOI18N
        jLabel1.setText("Usuario:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 20, 0);
        jPanel2.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Droid Sans", 0, 12)); // NOI18N
        jLabel2.setText("Contraseña:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 6;
        jPanel2.add(jLabel2, gridBagConstraints);

        txtUsuario.setFont(new java.awt.Font("Droid Sans", 0, 12)); // NOI18N
        txtUsuario.setPreferredSize(new java.awt.Dimension(180, 21));
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 20, 0);
        jPanel2.add(txtUsuario, gridBagConstraints);

        btnAcceso.setFont(new java.awt.Font("Droid Sans", 1, 12)); // NOI18N
        btnAcceso.setText("INGRESAR");
        btnAcceso.setToolTipText("Ingresar");
        btnAcceso.setBorderPainted(false);
        btnAcceso.setContentAreaFilled(false);
        btnAcceso.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAcceso.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAcceso.setMargin(new java.awt.Insets(2, 5, 2, 5));
        btnAcceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccesoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(20, 50, 0, 0);
        jPanel2.add(btnAcceso, gridBagConstraints);

        jButton2.setFont(new java.awt.Font("Droid Sans", 1, 12)); // NOI18N
        jButton2.setText("SALIR");
        jButton2.setToolTipText("Salir");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 0, 0);
        jPanel2.add(jButton2, gridBagConstraints);

        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel2.add(txtPassword, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Droid Sans", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 204));
        jLabel3.setText("Sistema de Gestión Administrativa Institucional");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addContainerGap(311, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Panel p = new Panel();
        p.setBounds(20, 60, p.getWidth(), p.getHeight());
        jPanel1.add(p);           
        jPanel1.repaint();
    }//GEN-LAST:event_formWindowActivated

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnAccesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccesoActionPerformed
        String usuario="";
        String password;
        String mensaje ="";
        int contUsu=0;        
        JLabel lblMensaje = new JLabel();        
        lblMensaje.setFont(new Font("DroidSans",Font.PLAIN,12));
        //Datos del ResultSet
        String passComprueba = null;
        String nombrePersonal = null;
        String idRol = null;
        String idPersonal = null;
        String nombreRolLogeado = null;
        boolean habilitado = true;
        //Extrae usuario y password ingresados
        usuario = txtUsuario.getText();
        char[] pass = txtPassword.getPassword();
        password = new String(pass);
        //
        ClsAcceso acceso = new ClsAcceso();
        con = ClsConexion.getConection();
        {
            ResultSet datos;
            try
            {
                datos = acceso.SeleccionarUsuario(usuario, con);
                while(datos.next())//comprueba si el usuario existe
                {
                    //el usuario si existe   
                    contUsu++;               
                    //obtenemos el password
                    passComprueba = datos.getString("personal_password");
                    nombrePersonal= datos.getString("nombre");
                    idRol = datos.getString("rol_id");
                    idPersonal = datos.getString("personal_id");
                    nombreRolLogeado = datos.getString("rol_nombre");
                    habilitado = !datos.getString("personal_estado").equals("I");
                }
            }
            catch(Exception ex)
            {
                System.out.println(ex);
            }
        }
        ClsConexion.closeConnection(con);
        
        //el usuario existe
        if(contUsu==1)
        {
            //el usuario esta habilitado
            if(habilitado)
            {
                 //compara passwords
                if(DigestUtils.shaHex(password).equals(passComprueba))
                {
                    mensaje = "Bienvenido(a):\n"+nombrePersonal;
                    lblMensaje.setText(mensaje);
                    JOptionPane.showMessageDialog(this, lblMensaje,"Acceso correcto",JOptionPane.INFORMATION_MESSAGE);
                    FrmPrincipal.usuarioLogeado = nombrePersonal;
                    FrmPrincipal.idRolLogeado = idRol;
                    FrmPrincipal.idPersonalLogeado = idPersonal;
                    FrmPrincipal.nombreRolLogeado = nombreRolLogeado;
                    PckInterfaces.FrmPrincipal obj = new PckInterfaces.FrmPrincipal();
                    obj.pack();
                    obj.setLocationRelativeTo(null);
                    obj.setVisible(true);
                    //obj.toFront();
                    obj.setExtendedState(6); //JFrame.MAXIMIZED_BOTH
                    //obj.setExtendedState(0); //JFrame.NORMAL
                    
                    this.dispose();
                }
                else
                {
                    mensaje = "La contraseña es incorrecta";
                    lblMensaje.setText(mensaje);
                    JOptionPane.showMessageDialog(this, lblMensaje,"Acceso incorrecto",JOptionPane.ERROR_MESSAGE);
                    txtPassword.requestFocus();
                }
            }
            else
            {
                mensaje ="El usuario no existe o a sido desactivado";
                lblMensaje.setText(mensaje);
                JOptionPane.showMessageDialog(this, lblMensaje,"Acceso incorrecto",JOptionPane.ERROR_MESSAGE);
                txtUsuario.requestFocus();
            }
        }
        else if(contUsu==0)
        {
            mensaje ="El usuario no existe o a sido desactivado";
            lblMensaje.setText(mensaje);
            JOptionPane.showMessageDialog(this, lblMensaje,"Acceso incorrecto",JOptionPane.ERROR_MESSAGE);
            txtUsuario.requestFocus();
        }
        
    }//GEN-LAST:event_btnAccesoActionPerformed

    private void txtUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) 
        {
              btnAccesoActionPerformed(null);
        }
    }//GEN-LAST:event_txtUsuarioKeyPressed

    private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) 
        {
              btnAccesoActionPerformed(null);
        }
    }//GEN-LAST:event_txtPasswordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMpsLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMpsLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMpsLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMpsLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMpsLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceso;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

}
