/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PckInterfaces;

import PckEntidad.ClsEntidadNivel;
import prymatricula.ClsMisc.miRender;
import PckNegocio.ClsNivel;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import prymatricula.ClsMisc;

/**
 *
 * @author Sistemas
 */
public class FrmNivel extends javax.swing.JInternalFrame {
    String nivelCodigo;
    
    /**
     * Creates new form FrmNivel
     */
    public FrmNivel() {
        initComponents();
        
        actualizarTabla();
    }
    
    private void actualizarTabla()
    {        
        String titulos[] = {"ID","Nombre"};
        ClsNivel niveles = new ClsNivel();
        ArrayList<ClsEntidadNivel> nivel = niveles.SeleccionarNivel();
        Iterator it = nivel.iterator();
        DefaultTableModel dtm = new DefaultTableModel(null,titulos){ 
        public boolean isCellEditable(int rowIndex,int columnIndex){return false;} 
        };    
        String fila[] = new String[3];
        while(it.hasNext())
        {
            ClsEntidadNivel Nivel = new ClsEntidadNivel();            
            Nivel = (ClsEntidadNivel) it.next();            
            fila[0] = Nivel.getNivel_id();
            fila[1] = Nivel.getNivel_nombre();     
            dtm.addRow(fila);
            
        }
        tblNivel.setModel(dtm);
        tblNivel.removeColumn(tblNivel.getColumnModel().getColumn(0)); 
        
        //CENRAR COLUMNAS Y FILAS (ClsMisc)
        TableCellRenderer tcr =  tblNivel.getTableHeader().getDefaultRenderer();                       
        miRender mr = new miRender(tcr);
        mr.getTableCellRendererComponent(tblNivel, fila, isSelected, isIcon, WIDTH, 0);
        //public boolean isCellEditable(int rowIndex, int columnIndex) {
        //if (columnIndex==4) {
        //return true;  //La columna 4 es editable.
        //}
        //return false;  //El resto de celdas no son editables.
        //}
    }
    
    private void activaBotones(boolean guardar,boolean modificar)
    {
        btnGuardar.setEnabled(guardar);
        btnModificar.setEnabled(modificar);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNivel = new javax.swing.JTable();
        txtNombre = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();

        setTitle("Nivel");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PckImages/nivel.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 130, 50));

        jLabel2.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, 20));

        tblNivel.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        tblNivel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        tblNivel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNivelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNivel);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 240, 190));

        txtNombre.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        txtNombre.setEnabled(false);
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreKeyReleased(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 90, -1));

        btnGuardar.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PckIconos/accept.png"))); // NOI18N
        btnGuardar.setText("Agregar");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 120, -1));

        btnModificar.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PckIconos/edit.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setEnabled(false);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 120, 40));

        btnSalir.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PckIconos/back.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 120, 40));

        btnNuevo.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PckIconos/add.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 120, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        ClsNivel nivel = new ClsNivel();
        ClsEntidadNivel enivel = new ClsEntidadNivel();
        enivel.setNivel_nombre(txtNombre.getText());        
        nivel.AgregarNivel(enivel);
        activaBotones(false,false);
        txtNombre.setText("");
        txtNombre.setEnabled(false); 
        actualizarTabla();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
       this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        activaBotones(true,false);
        txtNombre.setEnabled(true);
        txtNombre.requestFocus();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void tblNivelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNivelMouseClicked
        int reg;
        DefaultTableModel dtm = new DefaultTableModel();
        reg = tblNivel.getSelectedRow();
        if(reg == -1)
        {
        JOptionPane.showMessageDialog(null, "Debe Seleccionar un registro");
        }
        else
        {
        dtm = (DefaultTableModel)tblNivel.getModel();
        nivelCodigo = ((String) dtm.getValueAt(reg, 0));        
        txtNombre.setText((String) dtm.getValueAt(reg, 1));
        
        txtNombre.setEnabled(true); 
        activaBotones(false,true);
        
        
        }
    }//GEN-LAST:event_tblNivelMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        ClsNivel nivel = new ClsNivel();
        ClsEntidadNivel enivel = new ClsEntidadNivel();
        enivel.setNivel_nombre(txtNombre.getText());        
        nivel.ModificarNivel(enivel,nivelCodigo);
        activaBotones(false,false);
        txtNombre.setText("");
        txtNombre.setEnabled(false);
        actualizarTabla();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void txtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyReleased
        ClsMisc misc = new ClsMisc();
        txtNombre.setText(misc.convertirMayu(txtNombre.getText()));
    }//GEN-LAST:event_txtNombreKeyReleased
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblNivel;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
