/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package PckInterfaces;


import PckConexion.ClsConexion;
import PckEntidad.ClsEntidadAlumnoPago;
import PckEntidad.ClsEntidadNivel;
import PckEntidad.ClsEntidadPeriodo;
import PckEntidad.ClsEntidadProducto;
import PckEntidad.ClsEntidadSeccion;

import PckNegocio.ClsAlumno;
import PckNegocio.ClsNivel;
import PckNegocio.ClsPeriodo;
import PckNegocio.ClsProducto;
import PckNegocio.ClsSeccion;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;

import java.sql.Connection;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import prymatricula.ClsMisc;
import static prymatricula.ClsMisc.obtenerAnioActual;

/**
 *
 * @author kmv
 */
public class FrmProducto extends javax.swing.JInternalFrame {
String strCodigo="";
String nivel="";
String periodo="";
String seccion="";
String StrCodAlu="";
String nombre ="";
String venProducto="";
String actProducto="";
SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
Connection con = null;
//Listas para guardar codigos de los combos
  ArrayList<String> codigoNivel = new ArrayList();
  ArrayList<String> codigoPeriodo = new ArrayList();
  ArrayList<String> codigoSeccion = new ArrayList();
  ArrayList<String> codigoPeriodo2 = new ArrayList();
  ArrayList<String> codigoSeccion2 = new ArrayList();
    /**
     * Creates new form FrmProducto
     */
    public FrmProducto() {
        initComponents();
        
        grupo.add(radioPeriodo);
        grupo.add(radioSeccion);
        grupo.add(radioAlumno);
        
        String seleccionado = llenaCombo();
        cmbAnio.setSelectedItem(seleccionado); 
        cmbAnioo.setSelectedItem(seleccionado);
        
        Date abc = new Date();
        jdcFecha.setDate(abc);
        jdcFechap.setDate(abc);
        desactivaCampos();
      
        desactivaRadio();
        desactivaAsignacion();
        desactivaAlumno();        
        activaBotones(true,false,false,true,false);
        cmbAnio.setSelectedItem(obtenerAnioActual()); 
        actualizarTablaProducto();
        txtDescripcion.setLineWrap(true);
        
        //carga los combosde asignacion 
        cargaComboNivel();
        cargaComboPeriodo();
        if(cmbPeriodo.getSelectedIndex() != -1)
        {            
            cargaComboSeccion();
        }
       

        cargaPeriodoA();
        cargaSeccionA();
        
        if(!codigoSeccion.isEmpty())
        {
           actualizarTablaAlumno();  
        }
        
        
        //desactiva campos segun permisos
        if(!FrmPrincipal.mantenimientoProducto)            
        {
            desactivarBotones();
        }
        
        if(FrmPrincipal.asignarProducto)
        {
            tbdProducto.setEnabledAt(1, true);
        }
        else
        {
            tbdProducto.setEnabledAt(1, false);
        }
        
        
    }
    private void desactivarBotones()
    {
        btnNuevo.setEnabled(false);
        btnModificar.setEnabled(false);
        btnAgregar.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        tbdProducto = new javax.swing.JTabbedPane();
        jPanel11 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        cmbAnioo = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProducto = new javax.swing.JTable();
        cmbAnio = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        cmbSeccion2 = new javax.swing.JComboBox();
        cmbPeriodo2 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAlumno = new javax.swing.JTable();
        radioAlumno = new javax.swing.JRadioButton();
        jPanel9 = new javax.swing.JPanel();
        txtBusqueda = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        cmbNivel = new javax.swing.JComboBox();
        cmbPeriodo = new javax.swing.JComboBox();
        cmbSeccion = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        radioSeccion = new javax.swing.JRadioButton();
        radioPeriodo = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jdcFecha = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jdcFechap = new com.toedter.calendar.JDateChooser();
        jPanel8 = new javax.swing.JPanel();
        btnGenerar = new javax.swing.JButton();
        btnSalir1 = new javax.swing.JButton();

        setTitle("Producto");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Producto"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombre.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreKeyReleased(evt);
            }
        });
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 180, -1));

        txtPrecio.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
        });
        jPanel2.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 110, -1));

        txtStock.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        txtStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtStockKeyTyped(evt);
            }
        });
        jPanel2.add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 110, -1));

        jLabel3.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jLabel3.setText("Stock:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, 20));

        jLabel2.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jLabel2.setText("Precio:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 20));

        jLabel1.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jLabel1.setText("Nombre:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 20));

        jLabel4.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jLabel4.setText("Descripción:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        txtDescripcion.setColumns(20);
        txtDescripcion.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        txtDescripcion.setLineWrap(true);
        txtDescripcion.setRows(5);
        txtDescripcion.setWrapStyleWord(true);
        txtDescripcion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel2.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 220, 90));

        jLabel12.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jLabel12.setText("Año:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, 20));

        cmbAnioo.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        cmbAnioo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbAniooItemStateChanged(evt);
            }
        });
        jPanel2.add(cmbAnioo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 110, -1));

        jPanel11.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 520, 160));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Productos"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblProducto.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        tblProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProducto);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 480, 220));

        cmbAnio.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        cmbAnio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbAnioItemStateChanged(evt);
            }
        });
        jPanel4.add(cmbAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 110, -1));

        jPanel11.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 520, 270));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNuevo.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PckIconos/ic_library_add_black_24dp.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel3.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 70, 50));

        btnAgregar.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PckIconos/ic_save_black_24dp.png"))); // NOI18N
        btnAgregar.setText("Guardar");
        btnAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel3.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 80, 50));

        btnModificar.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PckIconos/ic_mode_edit_black_24dp.png"))); // NOI18N
        btnModificar.setText("Editar");
        btnModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel3.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 70, 50));

        btnSalir.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PckIconos/ic_exit_to_app_black_24dp.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel3.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 60, 50));

        btnEliminar.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PckIcoMenu/ic_delete_forever_black_24dp.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setToolTipText("Eliminar");
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel3.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, 50));

        jPanel11.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 520, 100));

        tbdProducto.addTab("Producto", jPanel11);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Asignar por Alumno"));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jLabel9.setText("Seleccione Sección:");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, 20));

        cmbSeccion2.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        cmbSeccion2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbSeccion2ItemStateChanged(evt);
            }
        });
        jPanel6.add(cmbSeccion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 220, -1));

        cmbPeriodo2.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        cmbPeriodo2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPeriodo2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPeriodo2ItemStateChanged(evt);
            }
        });
        jPanel6.add(cmbPeriodo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 220, -1));

        jLabel8.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jLabel8.setText("Seleccione Periodo:");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 120, 20));

        tblAlumno.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        tblAlumno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAlumno.setEnabled(false);
        tblAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAlumnoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblAlumno);

        jPanel6.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 300, 350));

        radioAlumno.setBackground(new java.awt.Color(255, 255, 255));
        radioAlumno.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioAlumnoItemStateChanged(evt);
            }
        });
        jPanel6.add(radioAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, -1, -1));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Búsqueda"));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBusqueda.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        txtBusqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBusquedaMouseClicked(evt);
            }
        });
        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyTyped(evt);
            }
        });
        jPanel9.add(txtBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 240, -1));

        jPanel6.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 300, 50));

        jPanel10.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 340, 540));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Asignar por"));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbNivel.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        cmbNivel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "GUARDERIA", "INICIAL" }));
        cmbNivel.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbNivelItemStateChanged(evt);
            }
        });
        jPanel7.add(cmbNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 118, -1));

        cmbPeriodo.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        cmbPeriodo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPeriodo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPeriodoItemStateChanged(evt);
            }
        });
        jPanel7.add(cmbPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 118, -1));

        cmbSeccion.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        cmbSeccion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel7.add(cmbSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 118, -1));

        jLabel5.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jLabel5.setText("Por Periodo:");
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 70, 20));

        jLabel6.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jLabel6.setText("Por Sección:");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 20));

        jLabel7.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jLabel7.setText("Nivel:");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 60, 20));

        radioSeccion.setBackground(new java.awt.Color(255, 255, 255));
        radioSeccion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioSeccionItemStateChanged(evt);
            }
        });
        jPanel7.add(radioSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 20, -1));

        radioPeriodo.setBackground(new java.awt.Color(255, 255, 255));
        radioPeriodo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioPeriodoItemStateChanged(evt);
            }
        });
        jPanel7.add(radioPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 20, -1));

        jPanel10.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 160, 230));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Asignación"));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jLabel10.setText("Fecha Vencimiento:");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 100, -1));

        jdcFecha.setEnabled(false);
        jdcFecha.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jPanel5.add(jdcFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 120, -1));

        jLabel11.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jLabel11.setText("Fecha Pedido:");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 70, -1));

        jdcFechap.setEnabled(false);
        jdcFechap.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jPanel5.add(jdcFechap, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 120, -1));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGenerar.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        btnGenerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PckIcoMenu/brightness-7.png"))); // NOI18N
        btnGenerar.setText("<html> <p>Generar</p> <p align=center>Deuda</p> </html>");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });
        jPanel8.add(btnGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 100, -1));

        btnSalir1.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        btnSalir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PckIconos/ic_exit_to_app_black_24dp.png"))); // NOI18N
        btnSalir1.setText("Salir");
        btnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir1ActionPerformed(evt);
            }
        });
        jPanel8.add(btnSalir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 40));

        jPanel5.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 120, 130));

        jPanel10.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 160, 300));

        tbdProducto.addTab("Asignar", jPanel10);

        jPanel1.add(tbdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 560, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductoMouseClicked
       int reg;
    DefaultTableModel defaultTableModel = new DefaultTableModel();
    reg = tblProducto.getSelectedRow();
        if(reg == -1)
        { JOptionPane.showMessageDialog(null, "Debe Seleccionar un registro"); 
        }
        else
        {
            try {
                defaultTableModel = (DefaultTableModel)tblProducto.getModel();
                strCodigo = ((String)defaultTableModel.getValueAt(reg, 0));
                txtNombre.setText((String) defaultTableModel.getValueAt(reg, 1));            
                txtPrecio.setText((String)defaultTableModel.getValueAt(reg, 2));
                txtDescripcion.setText((String)defaultTableModel.getValueAt(reg, 3));
                txtStock.setText((String)defaultTableModel.getValueAt(reg, 4));
                cmbAnioo.setSelectedItem((String)defaultTableModel.getValueAt(reg, 5));
                
            } catch (Exception ex) {
                Logger.getLogger(FrmPeriodo.class.getName()).log(Level.SEVERE, null, ex);
            }    
            
            if(!FrmPrincipal.mantenimientoProducto)            
            {
                desactivarBotones();
                activaRadio();
            }
            else
            {
                activaBotones(true,false,true,true,true);  
                activaCampos();
                activaRadio();
            }            
        }
      
    }//GEN-LAST:event_tblProductoMouseClicked

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        ClsEntidadProducto ep = new ClsEntidadProducto();
        ClsProducto p = new ClsProducto();
        
        ep.setNombre_Producto(txtNombre.getText());
        ep.setPrecio_Producto(txtPrecio.getText());
        ep.setDescripcion_Producto(txtDescripcion.getText());
        ep.setStock_Producto(txtStock.getText());
        ep.setAnio_Producto(cmbAnioo.getSelectedItem().toString()); 
        p.AgregarProducto(ep);
        
        activaBotones(true,false,false,true,false);
        limpiaCampos();
        actualizarTablaProducto();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtStockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStockKeyTyped
        char c = evt.getKeyChar();
        if (txtStock.getText().length()== 7 || !(Character.isDigit(c) ||
        (c == KeyEvent.VK_BACK_SPACE) ||
        (c == KeyEvent.VK_DELETE)))
        {
             
        evt.consume();
        }
    }//GEN-LAST:event_txtStockKeyTyped

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
       txtNombre.requestFocus();
       activaBotones(true,true,false,true,false);
       activaCampos();
       limpiaCampos();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped
        char c = evt.getKeyChar();
        if (txtPrecio.getText().length()== 7 || !(Character.isDigit(c) ||
        (c == KeyEvent.VK_BACK_SPACE) ||
        (c == KeyEvent.VK_DELETE)||
        (c == KeyEvent.VK_PERIOD) ))
        {             
        evt.consume();
        }
    }//GEN-LAST:event_txtPrecioKeyTyped

    private void txtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyReleased
        ClsMisc misc = new ClsMisc();
        txtNombre.setText(misc.convertirMayu(txtNombre.getText()));
    }//GEN-LAST:event_txtNombreKeyReleased

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        ClsEntidadProducto ep = new ClsEntidadProducto();
        ClsProducto p = new ClsProducto();
        
        ep.setNombre_Producto(txtNombre.getText());
        ep.setPrecio_Producto(txtPrecio.getText());
        ep.setDescripcion_Producto(txtDescripcion.getText());
        ep.setStock_Producto(txtStock.getText());
        ep.setAnio_Producto(cmbAnioo.getSelectedItem().toString()); 
        p.ModificaProducto(ep,strCodigo);
        
        activaBotones(true,false,false,true,false);
        limpiaCampos();
        actualizarTablaProducto();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void cmbSeccion2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbSeccion2ItemStateChanged
        if(cmbSeccion2.getSelectedIndex() != -1)
        {            
            actualizarTablaAlumno();                 
        }
    }//GEN-LAST:event_cmbSeccion2ItemStateChanged

    private void cmbPeriodo2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPeriodo2ItemStateChanged
        if(cmbPeriodo2.getSelectedIndex() != -1)
        {
            cargaSeccionA(); 
            actualizarTablaAlumno();
        }
    }//GEN-LAST:event_cmbPeriodo2ItemStateChanged

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        
        venProducto = formato.format(jdcFecha.getDate());
        actProducto = formato.format(jdcFechap.getDate());        
        
        try
        {
        Date fec1 = formato.parse(venProducto);
        Date fec2 = formato.parse(actProducto);
        if(fec1.before(fec2))
        {
            JOptionPane.showMessageDialog(null, "La fecha de vencimiento no puede ser menor a la fecha de pedido");
        }
        else    
        {   
            if(radioPeriodo.isSelected())
            {
                periodo = (String) cmbPeriodo.getSelectedItem();
                String idPeriodo = codigoPeriodo.get(cmbPeriodo.getSelectedIndex());
                String options[] = {"Aceptar","Cancelar"};
                int option = JOptionPane.showOptionDialog(this, "¿Seguro que desea generar deuda para "+periodo+"?", 
                "Confirmación", JOptionPane.NO_OPTION, JOptionPane.PLAIN_MESSAGE, null, options, options[0]);
                if(option == 0) // pressing OK button
                {
                prymatricula.AsignarProducto.asignarPeriodo(idPeriodo, strCodigo,actProducto,venProducto);
                JOptionPane.showMessageDialog(this, "Deuda generada correctamente");
                }
            }
            else if(radioSeccion.isSelected())
            {
                seccion = (String) cmbSeccion.getSelectedItem();
                String idSeccion = codigoSeccion.get(cmbSeccion.getSelectedIndex());
                String options[] = {"Aceptar","Cancelar"};
                int option = JOptionPane.showOptionDialog(this, "¿Seguro que desea generar deuda para "+seccion+"?", 
                "Confirmación", JOptionPane.NO_OPTION, JOptionPane.PLAIN_MESSAGE, null, options, options[0]);
                if(option == 0) // pressing OK button
                {
                prymatricula.AsignarProducto.asignarSeccion(idSeccion, strCodigo,actProducto,venProducto);
                JOptionPane.showMessageDialog(this, "Deuda generada correctamente");
                }
            }
            else if(radioAlumno.isSelected())
            {
                String options[] = {"Aceptar","Cancelar"};
                int option = JOptionPane.showOptionDialog(this, "¿Seguro que desea generar deuda para "+nombre+"?", 
                "Confirmación", JOptionPane.NO_OPTION, JOptionPane.PLAIN_MESSAGE, null, options, options[0]);
                if(option == 0) // pressing OK button
                {
                prymatricula.AsignarProducto.asignarAlumno(StrCodAlu, strCodigo,actProducto,venProducto);
                JOptionPane.showMessageDialog(this, "Deuda generada correctamente");
                }
                }
            }
        }        
    catch(ParseException | HeadlessException ex)
    {JOptionPane.showMessageDialog(this, "Por favor, Ingrese una Fecha de Vencimiento");
    }
       
       
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void cmbPeriodoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPeriodoItemStateChanged
        if(cmbPeriodo.getSelectedIndex() != -1)
        {
            cargaComboSeccion();
            System.out.println("Periodo: "+codigoPeriodo.get(cmbPeriodo.getSelectedIndex()));
        }
    }//GEN-LAST:event_cmbPeriodoItemStateChanged

    private void tblAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAlumnoMouseClicked
        int reg;
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        reg = tblAlumno.getSelectedRow();        
        if(reg == -1)
        {
        JOptionPane.showMessageDialog(null, "Primero debe seleccionar una opción de asignación");
        }
        else
        {
        defaultTableModel = (DefaultTableModel)tblAlumno.getModel();
        StrCodAlu = ((String)defaultTableModel.getValueAt(reg, 0));
        nombre = ((String) defaultTableModel.getValueAt(reg, 2));
        }
    }//GEN-LAST:event_tblAlumnoMouseClicked

    private void radioPeriodoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioPeriodoItemStateChanged
       if(radioPeriodo.isSelected())
       {
       activaItem(true,true,true);
       jdcFecha.setEnabled(true);
       jdcFechap.setEnabled(true);
       desactivaAlumno();
       }
    }//GEN-LAST:event_radioPeriodoItemStateChanged

    private void radioSeccionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioSeccionItemStateChanged
       if(radioSeccion.isSelected())
       {
       activaItem(true,true,true);
       jdcFecha.setEnabled(true);
       jdcFechap.setEnabled(true);
       desactivaAlumno();
       
       }
    }//GEN-LAST:event_radioSeccionItemStateChanged

    private void radioAlumnoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioAlumnoItemStateChanged
       if(radioAlumno.isSelected())
       {
       activaItem(false,false,false);
       jdcFecha.setEnabled(true);
       jdcFechap.setEnabled(true);
       activaAlumno();
       }
    }//GEN-LAST:event_radioAlumnoItemStateChanged

    private void cmbAnioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbAnioItemStateChanged
        if(cmbAnio.getSelectedIndex() != -1) //solo cargara si el index no es -1
        {            
            actualizarTablaProducto();
        }
    
    }//GEN-LAST:event_cmbAnioItemStateChanged

    private void cmbAniooItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbAniooItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAniooItemStateChanged

    private void cmbNivelItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbNivelItemStateChanged
        if(cmbNivel.getSelectedIndex() != -1)
        {
            cargaComboPeriodo();
            cargaComboSeccion();
        }
    }//GEN-LAST:event_cmbNivelItemStateChanged

    private void txtBusquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBusquedaMouseClicked
        int fin = txtBusqueda.getHeight();
        txtBusqueda.setSelectionStart(0);
        txtBusqueda.setSelectionEnd(fin);
    }//GEN-LAST:event_txtBusquedaMouseClicked

    private void txtBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyTyped

        String a = txtBusqueda.getText();
        if(a.equals(""))
        {
            actualizarTablaAlumno();
        }
        else
        {
            actualizarTablaAlumnoBusqueda(a);
        }
    }//GEN-LAST:event_txtBusquedaKeyTyped

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalir1ActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int choice = JOptionPane.showOptionDialog(null,"¿Seguro de eliminar el servicio seleccionado?",
            "Eliminar",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
        if (choice == JOptionPane.YES_OPTION)
        {
            ClsProducto prod = new ClsProducto();
            con = ClsConexion.getConection();
            prod.EliminarProducto(strCodigo, con);
            actualizarTablaProducto();
            activaBotones(true,false,false,true,false);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed
    private void desactivaAlumno()
    {
    cmbPeriodo2.setEnabled(false);
    cmbSeccion2.setEnabled(false);
    tblAlumno.setEnabled(false);
    }
    
    private void activaItem(boolean nivel,boolean periodo,boolean seccion)
    {
    cmbNivel.setEnabled(nivel);
    cmbPeriodo.setEnabled(periodo);
    cmbSeccion.setEnabled(seccion);    
    }
    
    private void activaAlumno()
    {
    cmbPeriodo2.setEnabled(true);
    cmbSeccion2.setEnabled(true);
    tblAlumno.setEnabled(true);
    }
    
    private void desactivaRadio()
    {   
    radioPeriodo.setEnabled(false);
    radioSeccion.setEnabled(false);
    radioAlumno.setEnabled(false);
    }
    
    private void activaRadio()
    {    
    radioPeriodo.setEnabled(true);
    radioSeccion.setEnabled(true);
    radioAlumno.setEnabled(true);
    }
    
    private void desactivaAsignacion()
    {    
    cmbNivel.setEnabled(false);
    cmbPeriodo.setEnabled(false);
    cmbSeccion.setEnabled(false);
    }
           
    private void desactivaCampos()
    {
    txtNombre.setEnabled(false);
    txtPrecio.setEnabled(false);
    txtStock.setEnabled(false);
    txtDescripcion.setEnabled(false);
    cmbAnioo.setEnabled(false);
    }
        
    private void activaCampos()
    {
    txtNombre.setEnabled(true);
    txtPrecio.setEnabled(true);
    txtStock.setEnabled(true);
    txtDescripcion.setEnabled(true);
    cmbAnioo.setEnabled(true); 
    }
    
    private void activaBotones(boolean nuevo,boolean agregar,boolean modificar,boolean salir,boolean eliminar)
    {
        btnNuevo.setEnabled(nuevo);
        btnAgregar.setEnabled(agregar);
        btnModificar.setEnabled(modificar);
        btnSalir.setEnabled(salir); 
        btnEliminar.setEnabled(eliminar);
    }
    
    private void limpiaCampos()
    {
    txtNombre.setText("");
    txtPrecio.setText("");
    txtStock.setText("");
    txtDescripcion.setText("");
    }
    private void actualizarTablaAlumnoBusqueda(String texto)
    {
        int p=1;
        String titulos[] = {"ID","N°","Apellidos y nombres","Sección","Periodo"};
        con = ClsConexion.getConection();
        ClsAlumno alumnos = new ClsAlumno();
        ArrayList<ClsEntidadAlumnoPago> alumnoo = alumnos.ListarAlumnoBusqueda(texto,con);
        Iterator iterator = alumnoo.iterator();
        DefaultTableModel defaultTableModel =new DefaultTableModel(null,titulos);               
        String fila[] = new String[12];                
        while(iterator.hasNext())
        {
            ClsEntidadAlumnoPago Alumno;
            Alumno = (ClsEntidadAlumnoPago) iterator.next();
            fila[0] = Alumno.getId_Matricula();
            fila[1] = String.valueOf(p);
            fila[2] = Alumno.getApellidos_Nombres();
            fila[3] = Alumno.getNombre_Seccion();
            fila[4] = Alumno.getNombre_Periodo();

                p++;
                defaultTableModel.addRow(fila);                

        }         
        ClsConexion.closeConnection(con);
        tblAlumno.setModel(defaultTableModel);
        tblAlumno.removeColumn(tblAlumno.getColumnModel().getColumn(0));
        TableColumn  columnaN =tblAlumno.getColumnModel().getColumn(0);
        columnaN.setPreferredWidth(12);
        TableColumn  columnaPer =tblAlumno.getColumnModel().getColumn(1);
        columnaPer.setPreferredWidth(150);
    }
    private void actualizarTablaProducto()
    {
        String titulos[] = {"Codigo","Nombre","Precio","Descripcion","Stock","Año"};
        ClsProducto productos = new ClsProducto();
        ArrayList<ClsEntidadProducto> producto = productos.ListarProducto();
        Iterator iterator = producto.iterator();
        DefaultTableModel defaultTableModel =new DefaultTableModel(null,titulos){
        public boolean isCellEditable(int rowIndex,int columnIndex){return false;} 
        };          
        String fila[] = new String[6];
        while(iterator.hasNext())
        {
            ClsEntidadProducto Producto = new ClsEntidadProducto();
            Producto = (ClsEntidadProducto) iterator.next();
            fila[0] = Producto.getId_Producto();
            fila[1] = Producto.getNombre_Producto();
            fila[2] = Producto.getPrecio_Producto();
            fila[3] = Producto.getDescripcion_Producto();
            fila[4] = Producto.getStock_Producto();
            fila[5] = Producto.getAnio_Producto();
            String anio = cmbAnio.getSelectedItem().toString();
            if (anio.equals(fila[5])) 
            {
            defaultTableModel.addRow(fila); 
            }

        }
        tblProducto.setModel(defaultTableModel);    
        tblProducto.removeColumn(tblProducto.getColumnModel().getColumn(0));
        TableColumn  columnaNombre =tblProducto.getColumnModel().getColumn(0);
                columnaNombre.setPreferredWidth(200);
        TableColumn  columnaApe =tblProducto.getColumnModel().getColumn(2);
        columnaApe.setPreferredWidth(220);  
    }
    
    private void cargaComboNivel()
    {
        ClsNivel niveles = new ClsNivel();
        ArrayList<ClsEntidadNivel> nivel =  niveles.SeleccionarNivel();
        Iterator it = nivel.iterator();
        DefaultComboBoxModel dtm = new DefaultComboBoxModel();
        dtm.removeAllElements();
        cmbNivel.removeAllItems();
                
        while(it.hasNext())
        {
        ClsEntidadNivel Nivel = new ClsEntidadNivel();
        Nivel = (ClsEntidadNivel) it.next();       
        codigoNivel.add(Nivel.getNivel_id());
        dtm.addElement(Nivel.getNivel_nombre());                
        }
        cmbNivel.setModel(dtm); 
    }
    private void cargaComboPeriodo()
    {
        codigoPeriodo.clear();
        ClsPeriodo periodos = new ClsPeriodo();
        ArrayList<ClsEntidadPeriodo> pperiodo =  periodos.ListarPeriodo();
        Iterator iterator = pperiodo.iterator();
        DefaultComboBoxModel DefaultComboBoxModel = new DefaultComboBoxModel();
        DefaultComboBoxModel.removeAllElements();
        cmbPeriodo.removeAllItems();
        String fila[] = new String[4];     
        while(iterator.hasNext())
        {
        ClsEntidadPeriodo Periodo = new ClsEntidadPeriodo();
        Periodo = (ClsEntidadPeriodo) iterator.next();               
        fila[0] = Periodo.getNombre_Periodo();
        fila[1] = Periodo.getEstado_Periodo();        
            if(Periodo.getEstado_Periodo().equals("Activo") &&                     
            codigoNivel.get(cmbNivel.getSelectedIndex()).equals(Periodo.getNivel_Id()))
            {   
            codigoPeriodo.add(Periodo.getId_Periodo());     
            DefaultComboBoxModel.addElement(Periodo.getNombre_Periodo());        
            }
        }
        cmbPeriodo.setModel(DefaultComboBoxModel);      
    }
    private void cargaComboSeccion()
    {
        codigoSeccion.clear();
        ClsSeccion secciones = new ClsSeccion();
        ArrayList<ClsEntidadSeccion> seccion =  secciones.ListarSeccion();
        Iterator it = seccion.iterator();
        DefaultComboBoxModel DefaultComboBoxModel = new DefaultComboBoxModel();
        DefaultComboBoxModel.removeAllElements();
        cmbSeccion.removeAllItems();
        String fila2[] = new String[5];        
        while(it.hasNext())
        {
        ClsEntidadSeccion Seccion = (ClsEntidadSeccion) it.next();             
        fila2[0] = Seccion.getNombre_Seccion();
        fila2[1] = Seccion.getEstado_Periodo();       
        fila2[3] = Seccion.getNombre_Periodo();        
            if (codigoPeriodo.get(cmbPeriodo.getSelectedIndex()).equals(Seccion.getId_Periodo())) 
            {
                codigoSeccion.add(Seccion.getId_Seccion());
                DefaultComboBoxModel.addElement(fila2[0]);
            }       
        }
        cmbSeccion.setModel(DefaultComboBoxModel);          
    }
    
    private void cargaPeriodoA()
    {
        ClsPeriodo periodos = new ClsPeriodo();
        ArrayList<ClsEntidadPeriodo> periodo =  periodos.ListarPeriodo();
        Iterator iterator = periodo.iterator();
        DefaultComboBoxModel DefaultComboBoxModel = new DefaultComboBoxModel();
        DefaultComboBoxModel.removeAllElements();
        cmbPeriodo2.removeAllItems();
        String fila[] = new String[4];     
        while(iterator.hasNext())
        {
        ClsEntidadPeriodo Periodo = new ClsEntidadPeriodo();
        Periodo = (ClsEntidadPeriodo) iterator.next();               
        fila[0] = Periodo.getNombre_Periodo();
        fila[1] = Periodo.getEstado_Periodo();        
            if(Periodo.getEstado_Periodo().equals("Activo"))
            {   
            codigoPeriodo2.add(Periodo.getId_Periodo());     
            DefaultComboBoxModel.addElement(Periodo.getNombre_Periodo());        
            }        
        }
        cmbPeriodo2.setModel(DefaultComboBoxModel);
        //cambia estado del combo a lleno
        //conComboPeriodo2=1;
    }
    
    private void cargaSeccionA()
    {
        codigoSeccion2.clear();
        ClsSeccion secciones = new ClsSeccion();
        ArrayList<ClsEntidadSeccion> seccion =  secciones.ListarSeccion();
        Iterator it = seccion.iterator();
        DefaultComboBoxModel DefaultComboBoxModel = new DefaultComboBoxModel();
        DefaultComboBoxModel.removeAllElements();
        cmbSeccion2.removeAllItems();
        String fila2[] = new String[5];        
        while(it.hasNext())
        {
        ClsEntidadSeccion Seccion = (ClsEntidadSeccion) it.next();             
        fila2[0] = Seccion.getNombre_Seccion();
        fila2[1] = Seccion.getEstado_Periodo();       
        fila2[3] = Seccion.getNombre_Periodo();
        
            if (codigoPeriodo2.get(cmbPeriodo2.getSelectedIndex()).equals(Seccion.getId_Periodo())) 
            {
                codigoSeccion2.add(Seccion.getId_Seccion());
                DefaultComboBoxModel.addElement(fila2[0]);
            }
        }
        cmbSeccion2.setModel(DefaultComboBoxModel); 
    }
   
    private void actualizarTablaAlumno()
    {
        String titulos[] = {"ID","N°","Apellidos y nombres"};
        con = ClsConexion.getConection();
        ClsAlumno alumnos = new ClsAlumno();
        ArrayList<ClsEntidadAlumnoPago> alumno = alumnos.ListarAlumnoPago(con);
        Iterator iterator = alumno.iterator();
        DefaultTableModel defaultTableModel =new DefaultTableModel(null,titulos){
        public boolean isCellEditable(int rowIndex,int columnIndex){return false;} 
        };                 
        String fila[] = new String[12];                
        int aux=1;
        while(iterator.hasNext())
        {
            ClsEntidadAlumnoPago Alumno = new ClsEntidadAlumnoPago();
            Alumno = (ClsEntidadAlumnoPago) iterator.next();
            fila[0] = Alumno.getId_Matricula();
            fila[1] = String.valueOf(aux);
            fila[2] = Alumno.getApellidos_Nombres();
            fila[3] = Alumno.getId_Seccion();                       
            if(fila[3].equals(codigoSeccion2.get(cmbSeccion2.getSelectedIndex())))
            {
                aux++;
                defaultTableModel.addRow(fila);                
            }
        }         
        ClsConexion.closeConnection(con);
        tblAlumno.setModel(defaultTableModel);
        tblAlumno.removeColumn(tblAlumno.getColumnModel().getColumn(0));
        TableColumn  columnaPer =tblAlumno.getColumnModel().getColumn(0);
        columnaPer.setPreferredWidth(10);
        TableColumn  columnaP =tblAlumno.getColumnModel().getColumn(1);
        columnaP.setPreferredWidth(200);
        TableCellRenderer tcr =  tblAlumno.getTableHeader().getDefaultRenderer();                       
        ClsMisc.miRender mr = new ClsMisc.miRender(tcr);
        mr.getTableCellRendererComponent(tblAlumno, fila, isSelected, isIcon, WIDTH, 0);
    }
    
    private String llenaCombo()
    {
        cmbAnio.removeAllItems();
        cmbAnioo.removeAllItems();
        //obtengo año actual
        int Anioactual = Integer.parseInt(obtenerAnioActual());   
        int burbuja[] = new int[4];
        //lleno la matriz inicial (2015-2014-2013-2012-2011)
        //es necesario ordenarla
        for (int i=0;i<4;i++)
        {
           burbuja[i] = Anioactual - i;
        }        
        int temp;
        for(int m=0;m<burbuja.length;m++)//recorre cada elemento
        {            
            for(int n=0;n<burbuja.length-1;n++)//el elemento es comparado con todos
            {                
                if(burbuja[n]>burbuja[n+1]) //+1 porque ya tomamos el valor 0
                {
                    temp = burbuja[n];
                    burbuja[n] = burbuja[n+1];
                    burbuja[n+1] = temp;
                }
            }
        }
        //agrego los años ordenados
        for(int o=0;o<burbuja.length;o++)
        {
            cmbAnio.addItem(String.valueOf(burbuja[o]));
            cmbAnioo.addItem(String.valueOf(burbuja[o]));
        }        
        //agrego los 4 años siguientes
        for (int j=1;j<5;j++)
        {
           cmbAnio.addItem(String.valueOf(Anioactual + j));
           cmbAnioo.addItem(String.valueOf(Anioactual + j));
        }
        
        return String.valueOf(Anioactual);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSalir1;
    private javax.swing.JComboBox cmbAnio;
    private javax.swing.JComboBox cmbAnioo;
    private javax.swing.JComboBox cmbNivel;
    private javax.swing.JComboBox cmbPeriodo;
    private javax.swing.JComboBox cmbPeriodo2;
    private javax.swing.JComboBox cmbSeccion;
    private javax.swing.JComboBox cmbSeccion2;
    private javax.swing.ButtonGroup grupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser jdcFecha;
    private com.toedter.calendar.JDateChooser jdcFechap;
    private javax.swing.JRadioButton radioAlumno;
    private javax.swing.JRadioButton radioPeriodo;
    private javax.swing.JRadioButton radioSeccion;
    private javax.swing.JTabbedPane tbdProducto;
    private javax.swing.JTable tblAlumno;
    private javax.swing.JTable tblProducto;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
