/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PckInterfaces;

import ClsEntidadReporte.ClsAlumnoCumpleanos;
import ClsEntidadReporte.ClsPadreMadreCumpleanos;
import PckConexion.ClsConexion;
import PckEntidad.ClsEntidadAlumnoPago;
import PckEntidad.ClsEntidadNivel;
import PckEntidad.ClsEntidadPeriodo;
import PckEntidad.ClsEntidadSeccion;
import PckNegocio.ClsAlumno;
import PckNegocio.ClsNivel;
import PckNegocio.ClsPeriodo;
import PckNegocio.ClsSeccion;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Sistemas
 */
public class FrmRptCumpleanos extends javax.swing.JInternalFrame {

    Connection con = null;
    //Codigos de los combos
    ArrayList<String> codigoNivel = new ArrayList();
    ArrayList<String> codigoPeriodo = new ArrayList();
    ArrayList<String> codigoSeccion = new ArrayList();
    private static final String LOGOTIPO= System.getProperty("user.dir")+"/Img/solr.jpg";
    /**
     * Creates new form FrmRptCumpleanos
     */
    public FrmRptCumpleanos() {
        initComponents();
        cargaComboNivel();
        cargaComboPeriodo();
        if(cmbPeriodo.getSelectedIndex() != -1)
        {            
            cargaComboSeccion();
        }
        grupo.add(rbnNivel);
        grupo.add(rbnPeriodo);
        grupo.add(rbnSeccion);
        rbnSeccion.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cmbNivel = new javax.swing.JComboBox();
        lblNivel = new javax.swing.JLabel();
        cmbPeriodo = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        cmbSeccion = new javax.swing.JComboBox();
        lblSeccion = new javax.swing.JLabel();
        rbnNivel = new javax.swing.JRadioButton();
        rbnSeccion = new javax.swing.JRadioButton();
        rbnPeriodo = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        btnDirectorio = new javax.swing.JButton();
        cbxExcel = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setTitle("Reporte cumpleaños");
        setPreferredSize(new java.awt.Dimension(734, 272));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(607, 200));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccione aula"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbNivel.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        cmbNivel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbNivel.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbNivelItemStateChanged(evt);
            }
        });
        jPanel2.add(cmbNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 180, -1));

        lblNivel.setBackground(new java.awt.Color(0, 0, 0));
        lblNivel.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        lblNivel.setText("Nivel:");
        jPanel2.add(lblNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 20));

        cmbPeriodo.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        cmbPeriodo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPeriodo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPeriodoItemStateChanged(evt);
            }
        });
        jPanel2.add(cmbPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 180, -1));

        jLabel1.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jLabel1.setText("Periodo:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 20));

        cmbSeccion.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jPanel2.add(cmbSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 180, -1));

        lblSeccion.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        lblSeccion.setText("Sección:");
        jPanel2.add(lblSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 20));

        rbnNivel.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jPanel2.add(rbnNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        rbnSeccion.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jPanel2.add(rbnSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));

        rbnPeriodo.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jPanel2.add(rbnPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 300, 180));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDirectorio.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        btnDirectorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PckIcoMenu/ic_search_black_24dp.png"))); // NOI18N
        btnDirectorio.setText("Ver Cumpleaños");
        btnDirectorio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDirectorio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDirectorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDirectorioActionPerformed(evt);
            }
        });
        jPanel3.add(btnDirectorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 120, 60));

        cbxExcel.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        cbxExcel.setText("exportar csv");
        cbxExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxExcelActionPerformed(evt);
            }
        });
        jPanel3.add(cbxExcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 90, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PckIcoMenu/file-excel.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, 30));

        btnSalir.setBackground(new java.awt.Color(153, 153, 153));
        btnSalir.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PckIconos/ic_exit_to_app_black_24dp.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setToolTipText("");
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel3.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 80, 60));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 290, 180));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbNivelItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbNivelItemStateChanged
        if(cmbNivel.getSelectedIndex() != -1)
        {
            cargaComboPeriodo();
            if(cmbPeriodo.getSelectedIndex() != -1)
            {            
                cargaComboSeccion();
            }
        }
    }//GEN-LAST:event_cmbNivelItemStateChanged

    private void cmbPeriodoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPeriodoItemStateChanged
        if(cmbPeriodo.getSelectedIndex() != -1)
        {

            System.out.println("Periodo: "+cmbPeriodo.getSelectedItem()+" ID: "+codigoPeriodo.get(cmbPeriodo.getSelectedIndex()));
            cargaComboSeccion();
        }

    }//GEN-LAST:event_cmbPeriodoItemStateChanged

    private void btnDirectorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDirectorioActionPerformed
        
        if(cbxExcel.isSelected())
        {
            if(rbnNivel.isSelected())
            {
                try 
                {
                    con = ClsConexion.getConection();
                    String cod = codigoNivel.get(cmbNivel.getSelectedIndex());
                    CallableStatement st = con.prepareCall("{call sp_R_CumpleanosNivel(?)}");
                    st.setString("pid_nivel", cod);
                    st.executeQuery();
                    JOptionPane.showMessageDialog(null, "Generado en: D:/cumpleanosNivel.csv");
                    ClsConexion.closeConnection(con);
                } catch (SQLException ex) {
                    Logger.getLogger(FrmRptCumpleanos.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, ex); 
                }
            }
            else if(rbnPeriodo.isSelected())
            {
                try 
                {
                    con = ClsConexion.getConection();
                    String cod = codigoPeriodo.get(cmbPeriodo.getSelectedIndex());
                    CallableStatement st = con.prepareCall("{call sp_R_CumpleanosPeriodo(?)}");
                    st.setString("pid_periodo", cod);
                    st.executeQuery();
                    JOptionPane.showMessageDialog(null, "Generado en: D:/cumpleanosPeriodo.csv");
                    ClsConexion.closeConnection(con);
                } catch (SQLException ex) {
                    Logger.getLogger(FrmRptCumpleanos.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, ex); 
                }
            }
            else if(rbnSeccion.isSelected())
            {
                try 
                {
                    con = ClsConexion.getConection();
                    String cod = codigoSeccion.get(cmbSeccion.getSelectedIndex());
                    CallableStatement st = con.prepareCall("{call sp_R_Cumpleanos(?)}");
                    st.setString("pid_seccion", cod);
                    st.executeQuery();
                    JOptionPane.showMessageDialog(null, "Generado en: D:/cumpleanosSeccion.csv");
                    ClsConexion.closeConnection(con);
                } catch (SQLException ex) {
                    Logger.getLogger(FrmRptCumpleanos.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, ex); 
                }
            }                
        }
        else
        {
            
        //arrayList (dataSource) para el reporte principal
        ArrayList<ClsAlumnoCumpleanos> dsAlumno = new ArrayList<ClsAlumnoCumpleanos>();
        
        ClsAlumno alumnos = new ClsAlumno();
        con = ClsConexion.getConection();
        ArrayList<ClsEntidadAlumnoPago> alumnoo
        = alumnos.ListarAlumnoPagoSeccion(codigoSeccion.get(cmbSeccion.getSelectedIndex()), con);

        Iterator iterator = alumnoo.iterator();
        while(iterator.hasNext())
        {
            ClsEntidadAlumnoPago Alumno;
            Alumno = (ClsEntidadAlumnoPago) iterator.next();

            //Se instancia la clase alumno asignando el nombre
            ClsAlumnoCumpleanos a = new ClsAlumnoCumpleanos(Alumno.getApellidos_Nombres(),Alumno.getNacimiento(),Alumno.getEdad());
            //asignamos al dataSource los alumnos obtenidos
            dsAlumno.add(a);
            String nombrePadre="";
            String fechanPadre = "";            

            String nombreMadre="";
            String fechanMadre = "";
            
            //obtenemos datos Padre y Madre
            try
            {

                ResultSet rs = alumnos.SeleccionarMatriculaFichaReporte(Alumno.getId_Matricula(), con);
                while(rs.next())
                {
                    nombrePadre = rs.getString("padre_apellido_paterno")+" "+rs.getString("padre_apellido_materno")+", "
                    + rs.getString("padre_nombre");
                    fechanPadre = rs.getString("padre_fecha_nacimiento");
                   

                    nombreMadre = rs.getString("madre_apellido_paterno")+" "+rs.getString("madre_apellido_materno")+", "
                    + rs.getString("madre_nombre");
                    fechanMadre = rs.getString("madre_fecha_nacimiento");
                   
                }

            }
            catch (Exception ex)
            {
                Logger.getLogger(FrmDirectorio.class.getName()).log(Level.SEVERE, null, ex);
            }
            //Asignamos a la Lista a traves del constructor
            for(int i=0;i<2;i++)
            {
                if(i==0)
                {
                    a.addPadreMadre(new ClsPadreMadreCumpleanos(nombrePadre,fechanPadre));
                }
                else
                {
                    a.addPadreMadre(new ClsPadreMadreCumpleanos(nombreMadre,fechanMadre));
                }

            }

        }
        ClsConexion.closeConnection(con);

        try {
            //principal
            System.out.print(System.getProperty("user.dir"));
            String  url7 ="/Reportes/rptCumpleanosPrincipal.jrxml";
            JasperDesign jasperDesign = JRXmlLoader.load(System.getProperty("user.dir") + url7);
            JasperReport ReportMain = JasperCompileManager.compileReport(jasperDesign);

            Map<String, Object> params = new HashMap();
            params.put("Seccion", (String)cmbSeccion.getSelectedItem());
            params.put("logo", LOGOTIPO);
            params.put("SUBREPORT_DIR", System.getProperty("user.dir") + "\\Reportes\\");
                JasperPrint print = JasperFillManager.fillReport(ReportMain, params, new JRBeanCollectionDataSource(dsAlumno));
                JasperViewer view = new JasperViewer(print, false);
                view.setTitle("Directorio por aula");
                view.setVisible(true);

            } catch (JRException ex)
            {
                Logger.getLogger(FrmDirectorio.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, ex);
            }
        }
    }//GEN-LAST:event_btnDirectorioActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void cbxExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxExcelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxExcelActionPerformed

    
    private void cargaComboNivel()
    {
        ClsNivel niveles = new ClsNivel();
        ArrayList<ClsEntidadNivel> nivel =  niveles.SeleccionarNivel();
        Iterator it = nivel.iterator();
        DefaultComboBoxModel dtm = new DefaultComboBoxModel();
        dtm.removeAllElements();
        cmbNivel.removeAllItems();
                
        while(it.hasNext())
        {
        ClsEntidadNivel Nivel;
        Nivel = (ClsEntidadNivel) it.next();       
        codigoNivel.add(Nivel.getNivel_id());
        dtm.addElement(Nivel.getNivel_nombre());                
        }
        cmbNivel.setModel(dtm); 
   }
   private void cargaComboPeriodo()
   {
        codigoPeriodo.clear();
        ClsPeriodo periodos = new ClsPeriodo();
        ArrayList<ClsEntidadPeriodo> periodo =  periodos.ListarPeriodo();
        Iterator iterator = periodo.iterator();
        DefaultComboBoxModel DefaultComboBoxModel = new DefaultComboBoxModel();
        DefaultComboBoxModel.removeAllElements();
        cmbPeriodo.removeAllItems();
            
        while(iterator.hasNext())
        {
        ClsEntidadPeriodo Periodo ;
        Periodo = (ClsEntidadPeriodo) iterator.next();               
            
            if(Periodo.getEstado_Periodo().equals("Activo") &&                     
            codigoNivel.get(cmbNivel.getSelectedIndex()).equals(Periodo.getNivel_Id()))
            {   
            codigoPeriodo.add(Periodo.getId_Periodo());     
            DefaultComboBoxModel.addElement(Periodo.getNombre_Periodo());        
            }
        }
        cmbPeriodo.setModel(DefaultComboBoxModel);       
   }
   private void cargaComboSeccion()
   {    
        codigoSeccion.clear();
        ClsSeccion secciones = new ClsSeccion();
        ArrayList<ClsEntidadSeccion> seccion =  secciones.ListarSeccion();
        Iterator it = seccion.iterator();
        DefaultComboBoxModel DefaultComboBoxModel = new DefaultComboBoxModel();
        DefaultComboBoxModel.removeAllElements();
        cmbSeccion.removeAllItems();
        String fila2[] = new String[5];        
        while(it.hasNext())
        {
        ClsEntidadSeccion Seccion = (ClsEntidadSeccion) it.next();             
        fila2[0] = Seccion.getNombre_Seccion();
        fila2[1] = Seccion.getEstado_Periodo();       
        fila2[3] = Seccion.getNombre_Periodo();
        
            if (codigoPeriodo.get(cmbPeriodo.getSelectedIndex()).equals(Seccion.getId_Periodo())) 
            {
                codigoSeccion.add(Seccion.getId_Seccion());
                DefaultComboBoxModel.addElement(fila2[0]);
            }       
        }
        cmbSeccion.setModel(DefaultComboBoxModel);         
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDirectorio;
    private javax.swing.JButton btnSalir;
    private javax.swing.JCheckBox cbxExcel;
    private javax.swing.JComboBox cmbNivel;
    private javax.swing.JComboBox cmbPeriodo;
    private javax.swing.JComboBox cmbSeccion;
    private javax.swing.ButtonGroup grupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JLabel lblSeccion;
    private javax.swing.JRadioButton rbnNivel;
    private javax.swing.JRadioButton rbnPeriodo;
    private javax.swing.JRadioButton rbnSeccion;
    // End of variables declaration//GEN-END:variables
}
