/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PckInterfaces;

import ClsEntidadReporte.ClsSexo;
import PckConexion.ClsConexion;
import PckEntidad.ClsEntidadMatricula;
import PckEntidad.ClsEntidadNivel;
import PckEntidad.ClsEntidadPeriodo;
import PckEntidad.ClsEntidadSeccion;
import PckNegocio.ClsMatricula;
import PckNegocio.ClsNivel;
import PckNegocio.ClsPeriodo;
import PckNegocio.ClsSeccion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import java.util.Map;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author John Kevin Montes De Oca Vizcarra
 * @email jkevin.mv@gmail.com
 */
public class FrmRptSexoAlumno extends javax.swing.JInternalFrame {

    ArrayList<String> codigoNivel = new ArrayList();
    ArrayList<String> codigoPeriodo = new ArrayList();
    String idPeriodo = "0";
    String idAula = "0";
    Connection con = null;
    
    private static final String LOGOTIPO= System.getProperty("user.dir")+"/Img/solr.jpg";
    /**
     * Creates new form FrmRprSexoAlumno
     */
    public FrmRptSexoAlumno() {
        initComponents();
        
        cargarComboNivel();
        cargarComboPeriodo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        cmbNivel = new javax.swing.JComboBox();
        cmbPeriodo = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnReporte = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setTitle("Rerporte Sexo por Aulas");
        setPreferredSize(new java.awt.Dimension(467, 270));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 100));
        jPanel1.setPreferredSize(new java.awt.Dimension(467, 270));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtro"));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbNivel.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        cmbNivel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "GUARDERIA", "INICIAL" }));
        cmbNivel.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbNivelItemStateChanged(evt);
            }
        });
        jPanel7.add(cmbNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 250, -1));

        cmbPeriodo.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        cmbPeriodo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel7.add(cmbPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 250, -1));

        jLabel1.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jLabel1.setText("Nivel:");
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 20));

        jLabel2.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jLabel2.setText("Periodo:");
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 20));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 400, 140));

        btnReporte.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        btnReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PckIconos/process.png"))); // NOI18N
        btnReporte.setText("Generar Reporte");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });
        jPanel1.add(btnReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 170, 40));

        jButton1.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PckIconos/ic_exit_to_app_black_24dp.png"))); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 110, 40));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbNivelItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbNivelItemStateChanged
        
        if(cmbNivel.getSelectedIndex() != -1)
        {
            cargarComboPeriodo();            
        }
        
    }//GEN-LAST:event_cmbNivelItemStateChanged

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
       
        int hombres = 0;
        int mujeres = 0;
        int alumnos = 0;
        int hombresTotal = 0;
        int mujeresTotal = 0;
        int alumnosTotal = 0;
        String sexo = "";
        
        ClsMatricula clsMatricula;
        ClsSeccion clsSeccion;
        ClsSexo clsSexo;
        
        ArrayList<ClsEntidadMatricula> arrayMatricula;
        ArrayList<ClsEntidadSeccion> arraySeccion;
        ArrayList<ClsSexo> arraySexo;
        
        ResultSet rsMatricula;
        con = ClsConexion.getConection();
        
        Map mapa;
        JasperPrint jprint;
        JasperViewer jview;
        String rJrxml = "/Reportes/RptSexo.jrxml";
        String rJasper = "/Reportes/RptSexo.jasper";

        idPeriodo = codigoPeriodo.get(cmbPeriodo.getSelectedIndex());
        clsMatricula = new ClsMatricula();
        clsSeccion = new ClsSeccion();        
        arraySeccion = clsSeccion.ListarSeccionPeriodo(idPeriodo);
        arraySexo = new ArrayList<>();
        
        for(ClsEntidadSeccion a : arraySeccion)
        {
            rsMatricula = clsMatricula.ListarMatriculaAula(a.getId_Seccion(),con);
            hombres = 0;
            mujeres = 0;
            alumnos = 0;
            try 
            {
                while(rsMatricula.next())
                {
                    sexo = rsMatricula.getString("sexo_alumno");
                    
                    if(sexo.equals("M"))
                    {
                        hombres++;
                    }
                    else if (sexo.equals("F"))
                    {
                        mujeres++;
                    }
                }
                
            } 
            catch (SQLException ex) 
            {
                Logger.getLogger(FrmRptSexoAlumno.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            alumnos = hombres + mujeres;
            
            hombresTotal = hombresTotal + hombres;
            mujeresTotal = mujeresTotal + mujeres;
            alumnosTotal = hombresTotal + mujeresTotal;
            
            clsSexo = new ClsSexo();
            clsSexo.setAula(a.getNombre_Seccion());
            clsSexo.setHombres(String.valueOf(hombres));
            clsSexo.setMujeres(String.valueOf(mujeres));
            clsSexo.setAlumnos(String.valueOf(alumnos));
            arraySexo.add(clsSexo); 
        }
        
        try 
        {
            mapa = new HashMap();
            mapa.put("hombrest", String.valueOf(hombresTotal));
            mapa.put("mujerest", String.valueOf(mujeresTotal));
            mapa.put("alumnost", String.valueOf(alumnosTotal));
            mapa.put("logo", LOGOTIPO);
            mapa.put("periodo", cmbPeriodo.getSelectedItem().toString());
            
            JRBeanCollectionDataSource ds = new JRBeanCollectionDataSource(arraySexo);
            JasperCompileManager.compileReportToFile(System.getProperty("user.dir") + rJrxml, System.getProperty("user.dir") + rJasper);
            jprint = JasperFillManager.fillReport(System.getProperty("user.dir") + rJasper, mapa, ds);
            jview = new JasperViewer(jprint, false);
            jview.setTitle("Reporte Sexo por Aulas");
            jview.setVisible(true);
            
        } catch (JRException ex) {
            Logger.getLogger(FrmRptSexoAlumno.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        ClsConexion.closeConnection(con);
        
    }//GEN-LAST:event_btnReporteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
        
    
    private void cargarComboNivel()
    {
        ClsNivel nivel = new ClsNivel();
        ArrayList<ClsEntidadNivel> arrayNivel =  nivel.SeleccionarNivel();        
        DefaultComboBoxModel dtm = new DefaultComboBoxModel();
        dtm.removeAllElements();
        cmbNivel.removeAllItems();
        for(ClsEntidadNivel n : arrayNivel)
        {            
            codigoNivel.add(n.getNivel_id());            
            dtm.addElement(n.getNivel_nombre()); 
        }
        cmbNivel.setModel(dtm); 
    }
    
    private void cargarComboPeriodo()
    {
        codigoPeriodo.clear();
        ClsPeriodo clsPeriodo = new ClsPeriodo();
        ArrayList<ClsEntidadPeriodo> arrayPeriodo =  clsPeriodo.ListarPeriodo();        
        DefaultComboBoxModel dcm = new DefaultComboBoxModel();
        dcm.removeAllElements();
        cmbPeriodo.removeAllItems();
        int nivelIndex=0;
        nivelIndex = cmbNivel.getSelectedIndex();
        for(ClsEntidadPeriodo p : arrayPeriodo)
        {            
            if(p.getEstado_Periodo().equals("Activo") && codigoNivel.get(nivelIndex).equals(p.getNivel_Id()))
            {
                codigoPeriodo.add(p.getId_Periodo());
                dcm.addElement(p.getNombre_Periodo());
            }
        }
        cmbPeriodo.setModel(dcm);       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReporte;
    private javax.swing.JComboBox cmbNivel;
    private javax.swing.JComboBox cmbPeriodo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
}
