/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PckInterfaces;

import PckConexion.ClsConexion;
import PckNegocio.ClsBoleta;
import java.sql.Connection;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Sistemas
 */
public class FrmRptBoleta extends javax.swing.JInternalFrame {

private Connection con = new ClsConexion().getConection();
Date ini;
Date fi;
Date actual = new Date();

SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
Calendar cal = new GregorianCalendar();

    /**
     * Creates new form FrmRptBoleta
     */
    public FrmRptBoleta() {
        
        initComponents();
        cal.setTimeInMillis(actual.getTime());
        cal.add(Calendar.DATE, -7);
        
        
        jdcFin.setDate(actual);
        
    java.sql.Date pasado = new java.sql.Date(cal.getTimeInMillis());
        
    jdcInicio.setDate(pasado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jdcInicio = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jdcFin = new com.toedter.calendar.JDateChooser();
        btnGenerar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setTitle("Reporte Boletas");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jdcInicio.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jPanel1.add(jdcInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 110, -1));

        jLabel1.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jLabel1.setText("Fecha Inicio:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Droid Sans", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 204));
        jLabel2.setText("Seleccione intervalo de fechas ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jLabel3.setText("Fecha Fin:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, -1, -1));

        jdcFin.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jPanel1.add(jdcFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 130, -1));

        btnGenerar.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        btnGenerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PckIconos/accept_page.png"))); // NOI18N
        btnGenerar.setLabel("<html> <p>Generar</p> <p align=center>Reportes</p> </html>");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 120, 50));

        jButton1.setFont(new java.awt.Font("Droid Sans", 0, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PckIconos/back.png"))); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 120, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
         //Pasando parámetros
        ini = jdcInicio.getDate();
        fi = jdcFin.getDate();
        String url ="/Reportes/RptBoletas.jasper";
        String auxi = formato.format(ini);
        String auxf = formato.format(fi);
        String total = "";
        ClsBoleta bol = new ClsBoleta();
        ResultSet tot;
        
        try 
        {
            con = ClsConexion.getConection();
            tot = bol.SeleccionarTotalBoleta(auxi, auxf, con);
            while(tot.next())
            {
                total = tot.getString("monto_histo");
            }
        } 
        catch (Exception ex) 
        {
            Logger.getLogger(FrmRptBoleta.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        JasperReport report;
                Map p = new HashMap();            
                 p.put("inicio", auxi);
                 p.put("fin", auxf);
                 p.put("total", total);
            JasperPrint print;

            try{
                print = JasperFillManager.fillReport(System.getProperty("user.dir")+url,p ,con);
                JasperViewer view = new JasperViewer(print,false);

                view.setTitle("Reporte General de Boletas");
                view.setVisible(true);
            }
            catch(JRException ex)
            {
                ex.printStackTrace();
                //JOptionPane.showMessageDialog(this, ex);
            }
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JDateChooser jdcFin;
    private com.toedter.calendar.JDateChooser jdcInicio;
    // End of variables declaration//GEN-END:variables
}
